// Code generated by "enumer -type=DiagnosticKind -json"; DO NOT EDIT.

package diag

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _DiagnosticKindName = "DiagUnexpectedTokenDiagFunctionInvalidIdentifierDiagFunctionInvalidParameterDefDiagFunctionInvalidOpeningBraceDiagFunctionBodyClosingBraceMissingDiagSectionInvalidDriveDiagSectionInvalidChanDiagSectionFormatUnrecognicedDiagPreprocessorUnknownDiagExpressionGroupedMissingClosingParenthesesDiagNumberLiteralInvalidExponentDiagNumberLiteralParseErrorDiagBicoLiteralParseErrorDiagVersionLiteralParserErrorDiagExpressionInvalidDiagBitwiseLiteralInvalidHexDiagBitwiseLiteralInvalidBinDiagExpressionReplacementMissingClosingParenthesesDiagWhileEndMissingDiagIfThenEndMissingDiagIfElseIfEndMissingDiagIfElseEndMissingDiagCallStatementMalformedDiagInvaliStatementSectionUnterminatedStringUnterminatedNumberFormatUnterminated"

var _DiagnosticKindIndex = [...]uint16{0, 19, 48, 79, 110, 145, 168, 190, 219, 242, 288, 320, 347, 372, 401, 422, 450, 478, 528, 547, 567, 589, 609, 635, 654, 673, 691, 715}

const _DiagnosticKindLowerName = "diagunexpectedtokendiagfunctioninvalididentifierdiagfunctioninvalidparameterdefdiagfunctioninvalidopeningbracediagfunctionbodyclosingbracemissingdiagsectioninvaliddrivediagsectioninvalidchandiagsectionformatunrecogniceddiagpreprocessorunknowndiagexpressiongroupedmissingclosingparenthesesdiagnumberliteralinvalidexponentdiagnumberliteralparseerrordiagbicoliteralparseerrordiagversionliteralparsererrordiagexpressioninvaliddiagbitwiseliteralinvalidhexdiagbitwiseliteralinvalidbindiagexpressionreplacementmissingclosingparenthesesdiagwhileendmissingdiagifthenendmissingdiagifelseifendmissingdiagifelseendmissingdiagcallstatementmalformeddiaginvalistatementsectionunterminatedstringunterminatednumberformatunterminated"

func (i DiagnosticKind) String() string {
	if i < 0 || i >= DiagnosticKind(len(_DiagnosticKindIndex)-1) {
		return fmt.Sprintf("DiagnosticKind(%d)", i)
	}
	return _DiagnosticKindName[_DiagnosticKindIndex[i]:_DiagnosticKindIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _DiagnosticKindNoOp() {
	var x [1]struct{}
	_ = x[UnexpectedToken-(0)]
	_ = x[FunctionInvalidIdentifier-(1)]
	_ = x[FunctionInvalidParameterDef-(2)]
	_ = x[FunctionInvalidOpeningBrace-(3)]
	_ = x[DiagFunctionBodyClosingBraceMissing-(4)]
	_ = x[SectionInvalidDrive-(5)]
	_ = x[SectionInvalidChan-(6)]
	_ = x[SectionFormatUnrecogniced-(7)]
	_ = x[PreprocessorUnknown-(8)]
	_ = x[ExpressionGroupedMissingClosingParentheses-(9)]
	_ = x[NumberLiteralInvalidExponent-(10)]
	_ = x[NumberLiteralParseError-(11)]
	_ = x[BicoLiteralParseError-(12)]
	_ = x[VersionLiteralParserError-(13)]
	_ = x[ExpressionInvalid-(14)]
	_ = x[BitwiseLiteralInvalidHex-(15)]
	_ = x[BitwiseLiteralInvalidBin-(16)]
	_ = x[ExpressionReplacementMissingClosingParentheses-(17)]
	_ = x[WhileEndMissing-(18)]
	_ = x[IfThenEndMissing-(19)]
	_ = x[IfElseIfEndMissing-(20)]
	_ = x[IfElseEndMissing-(21)]
	_ = x[CallStatementMalformed-(22)]
	_ = x[InvaliStatement-(23)]
	_ = x[SectionUnterminated-(24)]
	_ = x[StringUnterminated-(25)]
	_ = x[NumberFormatUnterminated-(26)]
}

var _DiagnosticKindValues = []DiagnosticKind{UnexpectedToken, FunctionInvalidIdentifier, FunctionInvalidParameterDef, FunctionInvalidOpeningBrace, DiagFunctionBodyClosingBraceMissing, SectionInvalidDrive, SectionInvalidChan, SectionFormatUnrecogniced, PreprocessorUnknown, ExpressionGroupedMissingClosingParentheses, NumberLiteralInvalidExponent, NumberLiteralParseError, BicoLiteralParseError, VersionLiteralParserError, ExpressionInvalid, BitwiseLiteralInvalidHex, BitwiseLiteralInvalidBin, ExpressionReplacementMissingClosingParentheses, WhileEndMissing, IfThenEndMissing, IfElseIfEndMissing, IfElseEndMissing, CallStatementMalformed, InvaliStatement, SectionUnterminated, StringUnterminated, NumberFormatUnterminated}

var _DiagnosticKindNameToValueMap = map[string]DiagnosticKind{
	_DiagnosticKindName[0:19]:         UnexpectedToken,
	_DiagnosticKindLowerName[0:19]:    UnexpectedToken,
	_DiagnosticKindName[19:48]:        FunctionInvalidIdentifier,
	_DiagnosticKindLowerName[19:48]:   FunctionInvalidIdentifier,
	_DiagnosticKindName[48:79]:        FunctionInvalidParameterDef,
	_DiagnosticKindLowerName[48:79]:   FunctionInvalidParameterDef,
	_DiagnosticKindName[79:110]:       FunctionInvalidOpeningBrace,
	_DiagnosticKindLowerName[79:110]:  FunctionInvalidOpeningBrace,
	_DiagnosticKindName[110:145]:      DiagFunctionBodyClosingBraceMissing,
	_DiagnosticKindLowerName[110:145]: DiagFunctionBodyClosingBraceMissing,
	_DiagnosticKindName[145:168]:      SectionInvalidDrive,
	_DiagnosticKindLowerName[145:168]: SectionInvalidDrive,
	_DiagnosticKindName[168:190]:      SectionInvalidChan,
	_DiagnosticKindLowerName[168:190]: SectionInvalidChan,
	_DiagnosticKindName[190:219]:      SectionFormatUnrecogniced,
	_DiagnosticKindLowerName[190:219]: SectionFormatUnrecogniced,
	_DiagnosticKindName[219:242]:      PreprocessorUnknown,
	_DiagnosticKindLowerName[219:242]: PreprocessorUnknown,
	_DiagnosticKindName[242:288]:      ExpressionGroupedMissingClosingParentheses,
	_DiagnosticKindLowerName[242:288]: ExpressionGroupedMissingClosingParentheses,
	_DiagnosticKindName[288:320]:      NumberLiteralInvalidExponent,
	_DiagnosticKindLowerName[288:320]: NumberLiteralInvalidExponent,
	_DiagnosticKindName[320:347]:      NumberLiteralParseError,
	_DiagnosticKindLowerName[320:347]: NumberLiteralParseError,
	_DiagnosticKindName[347:372]:      BicoLiteralParseError,
	_DiagnosticKindLowerName[347:372]: BicoLiteralParseError,
	_DiagnosticKindName[372:401]:      VersionLiteralParserError,
	_DiagnosticKindLowerName[372:401]: VersionLiteralParserError,
	_DiagnosticKindName[401:422]:      ExpressionInvalid,
	_DiagnosticKindLowerName[401:422]: ExpressionInvalid,
	_DiagnosticKindName[422:450]:      BitwiseLiteralInvalidHex,
	_DiagnosticKindLowerName[422:450]: BitwiseLiteralInvalidHex,
	_DiagnosticKindName[450:478]:      BitwiseLiteralInvalidBin,
	_DiagnosticKindLowerName[450:478]: BitwiseLiteralInvalidBin,
	_DiagnosticKindName[478:528]:      ExpressionReplacementMissingClosingParentheses,
	_DiagnosticKindLowerName[478:528]: ExpressionReplacementMissingClosingParentheses,
	_DiagnosticKindName[528:547]:      WhileEndMissing,
	_DiagnosticKindLowerName[528:547]: WhileEndMissing,
	_DiagnosticKindName[547:567]:      IfThenEndMissing,
	_DiagnosticKindLowerName[547:567]: IfThenEndMissing,
	_DiagnosticKindName[567:589]:      IfElseIfEndMissing,
	_DiagnosticKindLowerName[567:589]: IfElseIfEndMissing,
	_DiagnosticKindName[589:609]:      IfElseEndMissing,
	_DiagnosticKindLowerName[589:609]: IfElseEndMissing,
	_DiagnosticKindName[609:635]:      CallStatementMalformed,
	_DiagnosticKindLowerName[609:635]: CallStatementMalformed,
	_DiagnosticKindName[635:654]:      InvaliStatement,
	_DiagnosticKindLowerName[635:654]: InvaliStatement,
	_DiagnosticKindName[654:673]:      SectionUnterminated,
	_DiagnosticKindLowerName[654:673]: SectionUnterminated,
	_DiagnosticKindName[673:691]:      StringUnterminated,
	_DiagnosticKindLowerName[673:691]: StringUnterminated,
	_DiagnosticKindName[691:715]:      NumberFormatUnterminated,
	_DiagnosticKindLowerName[691:715]: NumberFormatUnterminated,
}

var _DiagnosticKindNames = []string{
	_DiagnosticKindName[0:19],
	_DiagnosticKindName[19:48],
	_DiagnosticKindName[48:79],
	_DiagnosticKindName[79:110],
	_DiagnosticKindName[110:145],
	_DiagnosticKindName[145:168],
	_DiagnosticKindName[168:190],
	_DiagnosticKindName[190:219],
	_DiagnosticKindName[219:242],
	_DiagnosticKindName[242:288],
	_DiagnosticKindName[288:320],
	_DiagnosticKindName[320:347],
	_DiagnosticKindName[347:372],
	_DiagnosticKindName[372:401],
	_DiagnosticKindName[401:422],
	_DiagnosticKindName[422:450],
	_DiagnosticKindName[450:478],
	_DiagnosticKindName[478:528],
	_DiagnosticKindName[528:547],
	_DiagnosticKindName[547:567],
	_DiagnosticKindName[567:589],
	_DiagnosticKindName[589:609],
	_DiagnosticKindName[609:635],
	_DiagnosticKindName[635:654],
	_DiagnosticKindName[654:673],
	_DiagnosticKindName[673:691],
	_DiagnosticKindName[691:715],
}

// DiagnosticKindString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func DiagnosticKindString(s string) (DiagnosticKind, error) {
	if val, ok := _DiagnosticKindNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _DiagnosticKindNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to DiagnosticKind values", s)
}

// DiagnosticKindValues returns all values of the enum
func DiagnosticKindValues() []DiagnosticKind {
	return _DiagnosticKindValues
}

// DiagnosticKindStrings returns a slice of all String values of the enum
func DiagnosticKindStrings() []string {
	strs := make([]string, len(_DiagnosticKindNames))
	copy(strs, _DiagnosticKindNames)
	return strs
}

// IsADiagnosticKind returns "true" if the value is listed in the enum definition. "false" otherwise
func (i DiagnosticKind) IsADiagnosticKind() bool {
	for _, v := range _DiagnosticKindValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for DiagnosticKind
func (i DiagnosticKind) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for DiagnosticKind
func (i *DiagnosticKind) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("DiagnosticKind should be a string, got %s", data)
	}

	var err error
	*i, err = DiagnosticKindString(s)
	return err
}
