// Code generated by "enumer -type=DiagnosticKind -json"; DO NOT EDIT.

package diag

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _DiagnosticKindName = "UnexpectedTokenFunctionInvalidIdentifierFunctionInvalidParameterDefFunctionInvalidBeforeOpeningBraceFunctionMissingOpeningBraceFunctionBodyClosingBraceMissingSectionInvalidDriveSectionInvalidChanSectionFormatUnrecognicedPreprocessorUnknownExpressionGroupedMissingClosingParenthesesNumberLiteralInvalidExponentNumberLiteralParseErrorBicoLiteralParseErrorVersionLiteralParserErrorExpressionInvalidBitwiseLiteralInvalidHexBitwiseLiteralInvalidBinExpressionReplacementMissingClosingParenthesesWhileEndMissingIfThenEndMissingIfElseIfEndMissingIfElseEndMissingCallStatementMalformedInvaliStatementSectionUnterminatedStringUnterminatedNumberFormatUnterminated"

var _DiagnosticKindIndex = [...]uint16{0, 15, 40, 67, 100, 127, 158, 177, 195, 220, 239, 281, 309, 332, 353, 378, 395, 419, 443, 489, 504, 520, 538, 554, 576, 591, 610, 628, 652}

const _DiagnosticKindLowerName = "unexpectedtokenfunctioninvalididentifierfunctioninvalidparameterdeffunctioninvalidbeforeopeningbracefunctionmissingopeningbracefunctionbodyclosingbracemissingsectioninvaliddrivesectioninvalidchansectionformatunrecognicedpreprocessorunknownexpressiongroupedmissingclosingparenthesesnumberliteralinvalidexponentnumberliteralparseerrorbicoliteralparseerrorversionliteralparsererrorexpressioninvalidbitwiseliteralinvalidhexbitwiseliteralinvalidbinexpressionreplacementmissingclosingparentheseswhileendmissingifthenendmissingifelseifendmissingifelseendmissingcallstatementmalformedinvalistatementsectionunterminatedstringunterminatednumberformatunterminated"

func (i DiagnosticKind) String() string {
	if i < 0 || i >= DiagnosticKind(len(_DiagnosticKindIndex)-1) {
		return fmt.Sprintf("DiagnosticKind(%d)", i)
	}
	return _DiagnosticKindName[_DiagnosticKindIndex[i]:_DiagnosticKindIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _DiagnosticKindNoOp() {
	var x [1]struct{}
	_ = x[UnexpectedToken-(0)]
	_ = x[FunctionInvalidIdentifier-(1)]
	_ = x[FunctionInvalidParameterDef-(2)]
	_ = x[FunctionInvalidBeforeOpeningBrace-(3)]
	_ = x[FunctionMissingOpeningBrace-(4)]
	_ = x[FunctionBodyClosingBraceMissing-(5)]
	_ = x[SectionInvalidDrive-(6)]
	_ = x[SectionInvalidChan-(7)]
	_ = x[SectionFormatUnrecogniced-(8)]
	_ = x[PreprocessorUnknown-(9)]
	_ = x[ExpressionGroupedMissingClosingParentheses-(10)]
	_ = x[NumberLiteralInvalidExponent-(11)]
	_ = x[NumberLiteralParseError-(12)]
	_ = x[BicoLiteralParseError-(13)]
	_ = x[VersionLiteralParserError-(14)]
	_ = x[ExpressionInvalid-(15)]
	_ = x[BitwiseLiteralInvalidHex-(16)]
	_ = x[BitwiseLiteralInvalidBin-(17)]
	_ = x[ExpressionReplacementMissingClosingParentheses-(18)]
	_ = x[WhileEndMissing-(19)]
	_ = x[IfThenEndMissing-(20)]
	_ = x[IfElseIfEndMissing-(21)]
	_ = x[IfElseEndMissing-(22)]
	_ = x[CallStatementMalformed-(23)]
	_ = x[InvaliStatement-(24)]
	_ = x[SectionUnterminated-(25)]
	_ = x[StringUnterminated-(26)]
	_ = x[NumberFormatUnterminated-(27)]
}

var _DiagnosticKindValues = []DiagnosticKind{UnexpectedToken, FunctionInvalidIdentifier, FunctionInvalidParameterDef, FunctionInvalidBeforeOpeningBrace, FunctionMissingOpeningBrace, FunctionBodyClosingBraceMissing, SectionInvalidDrive, SectionInvalidChan, SectionFormatUnrecogniced, PreprocessorUnknown, ExpressionGroupedMissingClosingParentheses, NumberLiteralInvalidExponent, NumberLiteralParseError, BicoLiteralParseError, VersionLiteralParserError, ExpressionInvalid, BitwiseLiteralInvalidHex, BitwiseLiteralInvalidBin, ExpressionReplacementMissingClosingParentheses, WhileEndMissing, IfThenEndMissing, IfElseIfEndMissing, IfElseEndMissing, CallStatementMalformed, InvaliStatement, SectionUnterminated, StringUnterminated, NumberFormatUnterminated}

var _DiagnosticKindNameToValueMap = map[string]DiagnosticKind{
	_DiagnosticKindName[0:15]:         UnexpectedToken,
	_DiagnosticKindLowerName[0:15]:    UnexpectedToken,
	_DiagnosticKindName[15:40]:        FunctionInvalidIdentifier,
	_DiagnosticKindLowerName[15:40]:   FunctionInvalidIdentifier,
	_DiagnosticKindName[40:67]:        FunctionInvalidParameterDef,
	_DiagnosticKindLowerName[40:67]:   FunctionInvalidParameterDef,
	_DiagnosticKindName[67:100]:       FunctionInvalidBeforeOpeningBrace,
	_DiagnosticKindLowerName[67:100]:  FunctionInvalidBeforeOpeningBrace,
	_DiagnosticKindName[100:127]:      FunctionMissingOpeningBrace,
	_DiagnosticKindLowerName[100:127]: FunctionMissingOpeningBrace,
	_DiagnosticKindName[127:158]:      FunctionBodyClosingBraceMissing,
	_DiagnosticKindLowerName[127:158]: FunctionBodyClosingBraceMissing,
	_DiagnosticKindName[158:177]:      SectionInvalidDrive,
	_DiagnosticKindLowerName[158:177]: SectionInvalidDrive,
	_DiagnosticKindName[177:195]:      SectionInvalidChan,
	_DiagnosticKindLowerName[177:195]: SectionInvalidChan,
	_DiagnosticKindName[195:220]:      SectionFormatUnrecogniced,
	_DiagnosticKindLowerName[195:220]: SectionFormatUnrecogniced,
	_DiagnosticKindName[220:239]:      PreprocessorUnknown,
	_DiagnosticKindLowerName[220:239]: PreprocessorUnknown,
	_DiagnosticKindName[239:281]:      ExpressionGroupedMissingClosingParentheses,
	_DiagnosticKindLowerName[239:281]: ExpressionGroupedMissingClosingParentheses,
	_DiagnosticKindName[281:309]:      NumberLiteralInvalidExponent,
	_DiagnosticKindLowerName[281:309]: NumberLiteralInvalidExponent,
	_DiagnosticKindName[309:332]:      NumberLiteralParseError,
	_DiagnosticKindLowerName[309:332]: NumberLiteralParseError,
	_DiagnosticKindName[332:353]:      BicoLiteralParseError,
	_DiagnosticKindLowerName[332:353]: BicoLiteralParseError,
	_DiagnosticKindName[353:378]:      VersionLiteralParserError,
	_DiagnosticKindLowerName[353:378]: VersionLiteralParserError,
	_DiagnosticKindName[378:395]:      ExpressionInvalid,
	_DiagnosticKindLowerName[378:395]: ExpressionInvalid,
	_DiagnosticKindName[395:419]:      BitwiseLiteralInvalidHex,
	_DiagnosticKindLowerName[395:419]: BitwiseLiteralInvalidHex,
	_DiagnosticKindName[419:443]:      BitwiseLiteralInvalidBin,
	_DiagnosticKindLowerName[419:443]: BitwiseLiteralInvalidBin,
	_DiagnosticKindName[443:489]:      ExpressionReplacementMissingClosingParentheses,
	_DiagnosticKindLowerName[443:489]: ExpressionReplacementMissingClosingParentheses,
	_DiagnosticKindName[489:504]:      WhileEndMissing,
	_DiagnosticKindLowerName[489:504]: WhileEndMissing,
	_DiagnosticKindName[504:520]:      IfThenEndMissing,
	_DiagnosticKindLowerName[504:520]: IfThenEndMissing,
	_DiagnosticKindName[520:538]:      IfElseIfEndMissing,
	_DiagnosticKindLowerName[520:538]: IfElseIfEndMissing,
	_DiagnosticKindName[538:554]:      IfElseEndMissing,
	_DiagnosticKindLowerName[538:554]: IfElseEndMissing,
	_DiagnosticKindName[554:576]:      CallStatementMalformed,
	_DiagnosticKindLowerName[554:576]: CallStatementMalformed,
	_DiagnosticKindName[576:591]:      InvaliStatement,
	_DiagnosticKindLowerName[576:591]: InvaliStatement,
	_DiagnosticKindName[591:610]:      SectionUnterminated,
	_DiagnosticKindLowerName[591:610]: SectionUnterminated,
	_DiagnosticKindName[610:628]:      StringUnterminated,
	_DiagnosticKindLowerName[610:628]: StringUnterminated,
	_DiagnosticKindName[628:652]:      NumberFormatUnterminated,
	_DiagnosticKindLowerName[628:652]: NumberFormatUnterminated,
}

var _DiagnosticKindNames = []string{
	_DiagnosticKindName[0:15],
	_DiagnosticKindName[15:40],
	_DiagnosticKindName[40:67],
	_DiagnosticKindName[67:100],
	_DiagnosticKindName[100:127],
	_DiagnosticKindName[127:158],
	_DiagnosticKindName[158:177],
	_DiagnosticKindName[177:195],
	_DiagnosticKindName[195:220],
	_DiagnosticKindName[220:239],
	_DiagnosticKindName[239:281],
	_DiagnosticKindName[281:309],
	_DiagnosticKindName[309:332],
	_DiagnosticKindName[332:353],
	_DiagnosticKindName[353:378],
	_DiagnosticKindName[378:395],
	_DiagnosticKindName[395:419],
	_DiagnosticKindName[419:443],
	_DiagnosticKindName[443:489],
	_DiagnosticKindName[489:504],
	_DiagnosticKindName[504:520],
	_DiagnosticKindName[520:538],
	_DiagnosticKindName[538:554],
	_DiagnosticKindName[554:576],
	_DiagnosticKindName[576:591],
	_DiagnosticKindName[591:610],
	_DiagnosticKindName[610:628],
	_DiagnosticKindName[628:652],
}

// DiagnosticKindString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func DiagnosticKindString(s string) (DiagnosticKind, error) {
	if val, ok := _DiagnosticKindNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _DiagnosticKindNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to DiagnosticKind values", s)
}

// DiagnosticKindValues returns all values of the enum
func DiagnosticKindValues() []DiagnosticKind {
	return _DiagnosticKindValues
}

// DiagnosticKindStrings returns a slice of all String values of the enum
func DiagnosticKindStrings() []string {
	strs := make([]string, len(_DiagnosticKindNames))
	copy(strs, _DiagnosticKindNames)
	return strs
}

// IsADiagnosticKind returns "true" if the value is listed in the enum definition. "false" otherwise
func (i DiagnosticKind) IsADiagnosticKind() bool {
	for _, v := range _DiagnosticKindValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for DiagnosticKind
func (i DiagnosticKind) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for DiagnosticKind
func (i *DiagnosticKind) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("DiagnosticKind should be a string, got %s", data)
	}

	var err error
	*i, err = DiagnosticKindString(s)
	return err
}
