// Code generated by "enumer -type=DiagnosticSeverity -json"; DO NOT EDIT.

package diag

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _DiagnosticSeverityName = "SeverityError"

var _DiagnosticSeverityIndex = [...]uint8{0, 13}

const _DiagnosticSeverityLowerName = "severityerror"

func (i DiagnosticSeverity) String() string {
	if i < 0 || i >= DiagnosticSeverity(len(_DiagnosticSeverityIndex)-1) {
		return fmt.Sprintf("DiagnosticSeverity(%d)", i)
	}
	return _DiagnosticSeverityName[_DiagnosticSeverityIndex[i]:_DiagnosticSeverityIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _DiagnosticSeverityNoOp() {
	var x [1]struct{}
	_ = x[Error-(0)]
}

var _DiagnosticSeverityValues = []DiagnosticSeverity{Error}

var _DiagnosticSeverityNameToValueMap = map[string]DiagnosticSeverity{
	_DiagnosticSeverityName[0:13]:      Error,
	_DiagnosticSeverityLowerName[0:13]: Error,
}

var _DiagnosticSeverityNames = []string{
	_DiagnosticSeverityName[0:13],
}

// DiagnosticSeverityString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func DiagnosticSeverityString(s string) (DiagnosticSeverity, error) {
	if val, ok := _DiagnosticSeverityNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _DiagnosticSeverityNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to DiagnosticSeverity values", s)
}

// DiagnosticSeverityValues returns all values of the enum
func DiagnosticSeverityValues() []DiagnosticSeverity {
	return _DiagnosticSeverityValues
}

// DiagnosticSeverityStrings returns a slice of all String values of the enum
func DiagnosticSeverityStrings() []string {
	strs := make([]string, len(_DiagnosticSeverityNames))
	copy(strs, _DiagnosticSeverityNames)
	return strs
}

// IsADiagnosticSeverity returns "true" if the value is listed in the enum definition. "false" otherwise
func (i DiagnosticSeverity) IsADiagnosticSeverity() bool {
	for _, v := range _DiagnosticSeverityValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for DiagnosticSeverity
func (i DiagnosticSeverity) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for DiagnosticSeverity
func (i *DiagnosticSeverity) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("DiagnosticSeverity should be a string, got %s", data)
	}

	var err error
	*i, err = DiagnosticSeverityString(s)
	return err
}
