// Code generated by "enumer -type=DiagnosticKind -json"; DO NOT EDIT.

package diag

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _DiagnosticKindName = "UnexpectedTokenFunctionInvalidIdentifierFunctionInvalidParameterDefFunctionInvalidOpeningBraceFunctionBodyClosingBraceMissingSectionInvalidDriveSectionInvalidChanSectionFormatUnrecognicedPreprocessorUnknownExpressionGroupedMissingClosingParenthesesNumberLiteralInvalidExponentNumberLiteralParseErrorBicoLiteralParseErrorVersionLiteralParserErrorExpressionInvalidBitwiseLiteralInvalidHexBitwiseLiteralInvalidBinExpressionReplacementMissingClosingParenthesesWhileEndMissingIfThenEndMissingIfElseIfEndMissingIfElseEndMissingCallStatementMalformedInvaliStatementSectionUnterminatedStringUnterminatedNumberFormatUnterminated"

var _DiagnosticKindIndex = [...]uint16{0, 15, 40, 67, 94, 125, 144, 162, 187, 206, 248, 276, 299, 320, 345, 362, 386, 410, 456, 471, 487, 505, 521, 543, 558, 577, 595, 619}

const _DiagnosticKindLowerName = "unexpectedtokenfunctioninvalididentifierfunctioninvalidparameterdeffunctioninvalidopeningbracefunctionbodyclosingbracemissingsectioninvaliddrivesectioninvalidchansectionformatunrecognicedpreprocessorunknownexpressiongroupedmissingclosingparenthesesnumberliteralinvalidexponentnumberliteralparseerrorbicoliteralparseerrorversionliteralparsererrorexpressioninvalidbitwiseliteralinvalidhexbitwiseliteralinvalidbinexpressionreplacementmissingclosingparentheseswhileendmissingifthenendmissingifelseifendmissingifelseendmissingcallstatementmalformedinvalistatementsectionunterminatedstringunterminatednumberformatunterminated"

func (i DiagnosticKind) String() string {
	if i < 0 || i >= DiagnosticKind(len(_DiagnosticKindIndex)-1) {
		return fmt.Sprintf("DiagnosticKind(%d)", i)
	}
	return _DiagnosticKindName[_DiagnosticKindIndex[i]:_DiagnosticKindIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _DiagnosticKindNoOp() {
	var x [1]struct{}
	_ = x[UnexpectedToken-(0)]
	_ = x[FunctionInvalidIdentifier-(1)]
	_ = x[FunctionInvalidParameterDef-(2)]
	_ = x[FunctionInvalidOpeningBrace-(3)]
	_ = x[FunctionBodyClosingBraceMissing-(4)]
	_ = x[SectionInvalidDrive-(5)]
	_ = x[SectionInvalidChan-(6)]
	_ = x[SectionFormatUnrecogniced-(7)]
	_ = x[PreprocessorUnknown-(8)]
	_ = x[ExpressionGroupedMissingClosingParentheses-(9)]
	_ = x[NumberLiteralInvalidExponent-(10)]
	_ = x[NumberLiteralParseError-(11)]
	_ = x[BicoLiteralParseError-(12)]
	_ = x[VersionLiteralParserError-(13)]
	_ = x[ExpressionInvalid-(14)]
	_ = x[BitwiseLiteralInvalidHex-(15)]
	_ = x[BitwiseLiteralInvalidBin-(16)]
	_ = x[ExpressionReplacementMissingClosingParentheses-(17)]
	_ = x[WhileEndMissing-(18)]
	_ = x[IfThenEndMissing-(19)]
	_ = x[IfElseIfEndMissing-(20)]
	_ = x[IfElseEndMissing-(21)]
	_ = x[CallStatementMalformed-(22)]
	_ = x[InvaliStatement-(23)]
	_ = x[SectionUnterminated-(24)]
	_ = x[StringUnterminated-(25)]
	_ = x[NumberFormatUnterminated-(26)]
}

var _DiagnosticKindValues = []DiagnosticKind{UnexpectedToken, FunctionInvalidIdentifier, FunctionInvalidParameterDef, FunctionInvalidOpeningBrace, FunctionBodyClosingBraceMissing, SectionInvalidDrive, SectionInvalidChan, SectionFormatUnrecogniced, PreprocessorUnknown, ExpressionGroupedMissingClosingParentheses, NumberLiteralInvalidExponent, NumberLiteralParseError, BicoLiteralParseError, VersionLiteralParserError, ExpressionInvalid, BitwiseLiteralInvalidHex, BitwiseLiteralInvalidBin, ExpressionReplacementMissingClosingParentheses, WhileEndMissing, IfThenEndMissing, IfElseIfEndMissing, IfElseEndMissing, CallStatementMalformed, InvaliStatement, SectionUnterminated, StringUnterminated, NumberFormatUnterminated}

var _DiagnosticKindNameToValueMap = map[string]DiagnosticKind{
	_DiagnosticKindName[0:15]:         UnexpectedToken,
	_DiagnosticKindLowerName[0:15]:    UnexpectedToken,
	_DiagnosticKindName[15:40]:        FunctionInvalidIdentifier,
	_DiagnosticKindLowerName[15:40]:   FunctionInvalidIdentifier,
	_DiagnosticKindName[40:67]:        FunctionInvalidParameterDef,
	_DiagnosticKindLowerName[40:67]:   FunctionInvalidParameterDef,
	_DiagnosticKindName[67:94]:        FunctionInvalidOpeningBrace,
	_DiagnosticKindLowerName[67:94]:   FunctionInvalidOpeningBrace,
	_DiagnosticKindName[94:125]:       FunctionBodyClosingBraceMissing,
	_DiagnosticKindLowerName[94:125]:  FunctionBodyClosingBraceMissing,
	_DiagnosticKindName[125:144]:      SectionInvalidDrive,
	_DiagnosticKindLowerName[125:144]: SectionInvalidDrive,
	_DiagnosticKindName[144:162]:      SectionInvalidChan,
	_DiagnosticKindLowerName[144:162]: SectionInvalidChan,
	_DiagnosticKindName[162:187]:      SectionFormatUnrecogniced,
	_DiagnosticKindLowerName[162:187]: SectionFormatUnrecogniced,
	_DiagnosticKindName[187:206]:      PreprocessorUnknown,
	_DiagnosticKindLowerName[187:206]: PreprocessorUnknown,
	_DiagnosticKindName[206:248]:      ExpressionGroupedMissingClosingParentheses,
	_DiagnosticKindLowerName[206:248]: ExpressionGroupedMissingClosingParentheses,
	_DiagnosticKindName[248:276]:      NumberLiteralInvalidExponent,
	_DiagnosticKindLowerName[248:276]: NumberLiteralInvalidExponent,
	_DiagnosticKindName[276:299]:      NumberLiteralParseError,
	_DiagnosticKindLowerName[276:299]: NumberLiteralParseError,
	_DiagnosticKindName[299:320]:      BicoLiteralParseError,
	_DiagnosticKindLowerName[299:320]: BicoLiteralParseError,
	_DiagnosticKindName[320:345]:      VersionLiteralParserError,
	_DiagnosticKindLowerName[320:345]: VersionLiteralParserError,
	_DiagnosticKindName[345:362]:      ExpressionInvalid,
	_DiagnosticKindLowerName[345:362]: ExpressionInvalid,
	_DiagnosticKindName[362:386]:      BitwiseLiteralInvalidHex,
	_DiagnosticKindLowerName[362:386]: BitwiseLiteralInvalidHex,
	_DiagnosticKindName[386:410]:      BitwiseLiteralInvalidBin,
	_DiagnosticKindLowerName[386:410]: BitwiseLiteralInvalidBin,
	_DiagnosticKindName[410:456]:      ExpressionReplacementMissingClosingParentheses,
	_DiagnosticKindLowerName[410:456]: ExpressionReplacementMissingClosingParentheses,
	_DiagnosticKindName[456:471]:      WhileEndMissing,
	_DiagnosticKindLowerName[456:471]: WhileEndMissing,
	_DiagnosticKindName[471:487]:      IfThenEndMissing,
	_DiagnosticKindLowerName[471:487]: IfThenEndMissing,
	_DiagnosticKindName[487:505]:      IfElseIfEndMissing,
	_DiagnosticKindLowerName[487:505]: IfElseIfEndMissing,
	_DiagnosticKindName[505:521]:      IfElseEndMissing,
	_DiagnosticKindLowerName[505:521]: IfElseEndMissing,
	_DiagnosticKindName[521:543]:      CallStatementMalformed,
	_DiagnosticKindLowerName[521:543]: CallStatementMalformed,
	_DiagnosticKindName[543:558]:      InvaliStatement,
	_DiagnosticKindLowerName[543:558]: InvaliStatement,
	_DiagnosticKindName[558:577]:      SectionUnterminated,
	_DiagnosticKindLowerName[558:577]: SectionUnterminated,
	_DiagnosticKindName[577:595]:      StringUnterminated,
	_DiagnosticKindLowerName[577:595]: StringUnterminated,
	_DiagnosticKindName[595:619]:      NumberFormatUnterminated,
	_DiagnosticKindLowerName[595:619]: NumberFormatUnterminated,
}

var _DiagnosticKindNames = []string{
	_DiagnosticKindName[0:15],
	_DiagnosticKindName[15:40],
	_DiagnosticKindName[40:67],
	_DiagnosticKindName[67:94],
	_DiagnosticKindName[94:125],
	_DiagnosticKindName[125:144],
	_DiagnosticKindName[144:162],
	_DiagnosticKindName[162:187],
	_DiagnosticKindName[187:206],
	_DiagnosticKindName[206:248],
	_DiagnosticKindName[248:276],
	_DiagnosticKindName[276:299],
	_DiagnosticKindName[299:320],
	_DiagnosticKindName[320:345],
	_DiagnosticKindName[345:362],
	_DiagnosticKindName[362:386],
	_DiagnosticKindName[386:410],
	_DiagnosticKindName[410:456],
	_DiagnosticKindName[456:471],
	_DiagnosticKindName[471:487],
	_DiagnosticKindName[487:505],
	_DiagnosticKindName[505:521],
	_DiagnosticKindName[521:543],
	_DiagnosticKindName[543:558],
	_DiagnosticKindName[558:577],
	_DiagnosticKindName[577:595],
	_DiagnosticKindName[595:619],
}

// DiagnosticKindString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func DiagnosticKindString(s string) (DiagnosticKind, error) {
	if val, ok := _DiagnosticKindNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _DiagnosticKindNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to DiagnosticKind values", s)
}

// DiagnosticKindValues returns all values of the enum
func DiagnosticKindValues() []DiagnosticKind {
	return _DiagnosticKindValues
}

// DiagnosticKindStrings returns a slice of all String values of the enum
func DiagnosticKindStrings() []string {
	strs := make([]string, len(_DiagnosticKindNames))
	copy(strs, _DiagnosticKindNames)
	return strs
}

// IsADiagnosticKind returns "true" if the value is listed in the enum definition. "false" otherwise
func (i DiagnosticKind) IsADiagnosticKind() bool {
	for _, v := range _DiagnosticKindValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for DiagnosticKind
func (i DiagnosticKind) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for DiagnosticKind
func (i *DiagnosticKind) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("DiagnosticKind should be a string, got %s", data)
	}

	var err error
	*i, err = DiagnosticKindString(s)
	return err
}
