// Code generated by "enumer -type=TokenKind -json"; DO NOT EDIT.

package lexer

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _TokenKindName = "UnknownKeywordIfKeywordElseKeywordElseIfKeywordEndIfKeywordWhileKeywordEndWhileKeywordProcKeywordFuncKeywordReturnKeywordNamespaceNcKeywordNamespacePsKeywordNamespaceBdKeywordNamespaceChanSectionOperatorAssignOperatorAssignRawOperatorAssignIfBlankOperatorAddAssignOperatorSubtractAssignOperatorMultiplyAssignOperatorDivideAssignOperatorOrAssignOperatorAndAssignOperatorDeleteOperatorEqualOperatorUnequalOperatorLessThanOperatorLessThanEqualOperatorGreaterThanOperatorGreaterThanEqualOperatorLogAndOperatorLogOrOperatorStringConcatOperatorAddOperatorSubtractOperatorMultiplyOperatorDivideOperatorAndOperatorOrOperatorNegateLiteralIdentifierLiteralBlockNumberLiteralStringLiteralNumberFormatLiteralNumberLiteralHexLiteralNumberExLiteralNullLiteralTrueLiteralFalseSymbolLeftParenSymbolRightParenSymbolLeftBracketSymbolRightBracketSymbolLeftBraceSymbolRightBraceSymbolDotSymbolCommaSymbolDollarSymbolDollarParenCommentPreprocessorIncludePreprocessorUnknownEOFNewLine"

var _TokenKindIndex = [...]uint16{0, 7, 16, 27, 40, 52, 64, 79, 90, 101, 114, 132, 150, 168, 188, 195, 209, 226, 247, 264, 286, 308, 328, 344, 361, 375, 388, 403, 419, 440, 459, 483, 497, 510, 530, 541, 557, 573, 587, 598, 608, 622, 639, 657, 670, 689, 702, 712, 727, 738, 749, 761, 776, 792, 809, 827, 842, 858, 867, 878, 890, 907, 914, 933, 952, 955, 962}

const _TokenKindLowerName = "unknownkeywordifkeywordelsekeywordelseifkeywordendifkeywordwhilekeywordendwhilekeywordprockeywordfunckeywordreturnkeywordnamespacenckeywordnamespacepskeywordnamespacebdkeywordnamespacechansectionoperatorassignoperatorassignrawoperatorassignifblankoperatoraddassignoperatorsubtractassignoperatormultiplyassignoperatordivideassignoperatororassignoperatorandassignoperatordeleteoperatorequaloperatorunequaloperatorlessthanoperatorlessthanequaloperatorgreaterthanoperatorgreaterthanequaloperatorlogandoperatorlogoroperatorstringconcatoperatoraddoperatorsubtractoperatormultiplyoperatordivideoperatorandoperatororoperatornegateliteralidentifierliteralblocknumberliteralstringliteralnumberformatliteralnumberliteralhexliteralnumberexliteralnullliteraltrueliteralfalsesymbolleftparensymbolrightparensymbolleftbracketsymbolrightbracketsymbolleftbracesymbolrightbracesymboldotsymbolcommasymboldollarsymboldollarparencommentpreprocessorincludepreprocessorunknowneofnewline"

func (i TokenKind) String() string {
	if i < 0 || i >= TokenKind(len(_TokenKindIndex)-1) {
		return fmt.Sprintf("TokenKind(%d)", i)
	}
	return _TokenKindName[_TokenKindIndex[i]:_TokenKindIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _TokenKindNoOp() {
	var x [1]struct{}
	_ = x[Unknown-(0)]
	_ = x[KeywordIf-(1)]
	_ = x[KeywordElse-(2)]
	_ = x[KeywordElseIf-(3)]
	_ = x[KeywordEndIf-(4)]
	_ = x[KeywordWhile-(5)]
	_ = x[KeywordEndWhile-(6)]
	_ = x[KeywordProc-(7)]
	_ = x[KeywordFunc-(8)]
	_ = x[KeywordReturn-(9)]
	_ = x[KeywordNamespaceNc-(10)]
	_ = x[KeywordNamespacePs-(11)]
	_ = x[KeywordNamespaceBd-(12)]
	_ = x[KeywordNamespaceChan-(13)]
	_ = x[Section-(14)]
	_ = x[OperatorAssign-(15)]
	_ = x[OperatorAssignRaw-(16)]
	_ = x[OperatorAssignIfBlank-(17)]
	_ = x[OperatorAddAssign-(18)]
	_ = x[OperatorSubtractAssign-(19)]
	_ = x[OperatorMultiplyAssign-(20)]
	_ = x[OperatorDivideAssign-(21)]
	_ = x[OperatorOrAssign-(22)]
	_ = x[OperatorAndAssign-(23)]
	_ = x[OperatorDelete-(24)]
	_ = x[OperatorEqual-(25)]
	_ = x[OperatorUnequal-(26)]
	_ = x[OperatorLessThan-(27)]
	_ = x[OperatorLessThanEqual-(28)]
	_ = x[OperatorGreaterThan-(29)]
	_ = x[OperatorGreaterThanEqual-(30)]
	_ = x[OperatorLogAnd-(31)]
	_ = x[OperatorLogOr-(32)]
	_ = x[OperatorStringConcat-(33)]
	_ = x[OperatorAdd-(34)]
	_ = x[OperatorSubtract-(35)]
	_ = x[OperatorMultiply-(36)]
	_ = x[OperatorDivide-(37)]
	_ = x[OperatorAnd-(38)]
	_ = x[OperatorOr-(39)]
	_ = x[OperatorNegate-(40)]
	_ = x[LiteralIdentifier-(41)]
	_ = x[LiteralBlockNumber-(42)]
	_ = x[LiteralString-(43)]
	_ = x[LiteralNumberFormat-(44)]
	_ = x[LiteralNumber-(45)]
	_ = x[LiteralHex-(46)]
	_ = x[LiteralNumberEx-(47)]
	_ = x[LiteralNull-(48)]
	_ = x[LiteralTrue-(49)]
	_ = x[LiteralFalse-(50)]
	_ = x[SymbolLeftParen-(51)]
	_ = x[SymbolRightParen-(52)]
	_ = x[SymbolLeftBracket-(53)]
	_ = x[SymbolRightBracket-(54)]
	_ = x[SymbolLeftBrace-(55)]
	_ = x[SymbolRightBrace-(56)]
	_ = x[SymbolDot-(57)]
	_ = x[SymbolComma-(58)]
	_ = x[SymbolDollar-(59)]
	_ = x[SymbolDollarParen-(60)]
	_ = x[Comment-(61)]
	_ = x[PreprocessorInclude-(62)]
	_ = x[PreprocessorUnknown-(63)]
	_ = x[EOF-(64)]
	_ = x[NewLine-(65)]
}

var _TokenKindValues = []TokenKind{Unknown, KeywordIf, KeywordElse, KeywordElseIf, KeywordEndIf, KeywordWhile, KeywordEndWhile, KeywordProc, KeywordFunc, KeywordReturn, KeywordNamespaceNc, KeywordNamespacePs, KeywordNamespaceBd, KeywordNamespaceChan, Section, OperatorAssign, OperatorAssignRaw, OperatorAssignIfBlank, OperatorAddAssign, OperatorSubtractAssign, OperatorMultiplyAssign, OperatorDivideAssign, OperatorOrAssign, OperatorAndAssign, OperatorDelete, OperatorEqual, OperatorUnequal, OperatorLessThan, OperatorLessThanEqual, OperatorGreaterThan, OperatorGreaterThanEqual, OperatorLogAnd, OperatorLogOr, OperatorStringConcat, OperatorAdd, OperatorSubtract, OperatorMultiply, OperatorDivide, OperatorAnd, OperatorOr, OperatorNegate, LiteralIdentifier, LiteralBlockNumber, LiteralString, LiteralNumberFormat, LiteralNumber, LiteralHex, LiteralNumberEx, LiteralNull, LiteralTrue, LiteralFalse, SymbolLeftParen, SymbolRightParen, SymbolLeftBracket, SymbolRightBracket, SymbolLeftBrace, SymbolRightBrace, SymbolDot, SymbolComma, SymbolDollar, SymbolDollarParen, Comment, PreprocessorInclude, PreprocessorUnknown, EOF, NewLine}

var _TokenKindNameToValueMap = map[string]TokenKind{
	_TokenKindName[0:7]:          Unknown,
	_TokenKindLowerName[0:7]:     Unknown,
	_TokenKindName[7:16]:         KeywordIf,
	_TokenKindLowerName[7:16]:    KeywordIf,
	_TokenKindName[16:27]:        KeywordElse,
	_TokenKindLowerName[16:27]:   KeywordElse,
	_TokenKindName[27:40]:        KeywordElseIf,
	_TokenKindLowerName[27:40]:   KeywordElseIf,
	_TokenKindName[40:52]:        KeywordEndIf,
	_TokenKindLowerName[40:52]:   KeywordEndIf,
	_TokenKindName[52:64]:        KeywordWhile,
	_TokenKindLowerName[52:64]:   KeywordWhile,
	_TokenKindName[64:79]:        KeywordEndWhile,
	_TokenKindLowerName[64:79]:   KeywordEndWhile,
	_TokenKindName[79:90]:        KeywordProc,
	_TokenKindLowerName[79:90]:   KeywordProc,
	_TokenKindName[90:101]:       KeywordFunc,
	_TokenKindLowerName[90:101]:  KeywordFunc,
	_TokenKindName[101:114]:      KeywordReturn,
	_TokenKindLowerName[101:114]: KeywordReturn,
	_TokenKindName[114:132]:      KeywordNamespaceNc,
	_TokenKindLowerName[114:132]: KeywordNamespaceNc,
	_TokenKindName[132:150]:      KeywordNamespacePs,
	_TokenKindLowerName[132:150]: KeywordNamespacePs,
	_TokenKindName[150:168]:      KeywordNamespaceBd,
	_TokenKindLowerName[150:168]: KeywordNamespaceBd,
	_TokenKindName[168:188]:      KeywordNamespaceChan,
	_TokenKindLowerName[168:188]: KeywordNamespaceChan,
	_TokenKindName[188:195]:      Section,
	_TokenKindLowerName[188:195]: Section,
	_TokenKindName[195:209]:      OperatorAssign,
	_TokenKindLowerName[195:209]: OperatorAssign,
	_TokenKindName[209:226]:      OperatorAssignRaw,
	_TokenKindLowerName[209:226]: OperatorAssignRaw,
	_TokenKindName[226:247]:      OperatorAssignIfBlank,
	_TokenKindLowerName[226:247]: OperatorAssignIfBlank,
	_TokenKindName[247:264]:      OperatorAddAssign,
	_TokenKindLowerName[247:264]: OperatorAddAssign,
	_TokenKindName[264:286]:      OperatorSubtractAssign,
	_TokenKindLowerName[264:286]: OperatorSubtractAssign,
	_TokenKindName[286:308]:      OperatorMultiplyAssign,
	_TokenKindLowerName[286:308]: OperatorMultiplyAssign,
	_TokenKindName[308:328]:      OperatorDivideAssign,
	_TokenKindLowerName[308:328]: OperatorDivideAssign,
	_TokenKindName[328:344]:      OperatorOrAssign,
	_TokenKindLowerName[328:344]: OperatorOrAssign,
	_TokenKindName[344:361]:      OperatorAndAssign,
	_TokenKindLowerName[344:361]: OperatorAndAssign,
	_TokenKindName[361:375]:      OperatorDelete,
	_TokenKindLowerName[361:375]: OperatorDelete,
	_TokenKindName[375:388]:      OperatorEqual,
	_TokenKindLowerName[375:388]: OperatorEqual,
	_TokenKindName[388:403]:      OperatorUnequal,
	_TokenKindLowerName[388:403]: OperatorUnequal,
	_TokenKindName[403:419]:      OperatorLessThan,
	_TokenKindLowerName[403:419]: OperatorLessThan,
	_TokenKindName[419:440]:      OperatorLessThanEqual,
	_TokenKindLowerName[419:440]: OperatorLessThanEqual,
	_TokenKindName[440:459]:      OperatorGreaterThan,
	_TokenKindLowerName[440:459]: OperatorGreaterThan,
	_TokenKindName[459:483]:      OperatorGreaterThanEqual,
	_TokenKindLowerName[459:483]: OperatorGreaterThanEqual,
	_TokenKindName[483:497]:      OperatorLogAnd,
	_TokenKindLowerName[483:497]: OperatorLogAnd,
	_TokenKindName[497:510]:      OperatorLogOr,
	_TokenKindLowerName[497:510]: OperatorLogOr,
	_TokenKindName[510:530]:      OperatorStringConcat,
	_TokenKindLowerName[510:530]: OperatorStringConcat,
	_TokenKindName[530:541]:      OperatorAdd,
	_TokenKindLowerName[530:541]: OperatorAdd,
	_TokenKindName[541:557]:      OperatorSubtract,
	_TokenKindLowerName[541:557]: OperatorSubtract,
	_TokenKindName[557:573]:      OperatorMultiply,
	_TokenKindLowerName[557:573]: OperatorMultiply,
	_TokenKindName[573:587]:      OperatorDivide,
	_TokenKindLowerName[573:587]: OperatorDivide,
	_TokenKindName[587:598]:      OperatorAnd,
	_TokenKindLowerName[587:598]: OperatorAnd,
	_TokenKindName[598:608]:      OperatorOr,
	_TokenKindLowerName[598:608]: OperatorOr,
	_TokenKindName[608:622]:      OperatorNegate,
	_TokenKindLowerName[608:622]: OperatorNegate,
	_TokenKindName[622:639]:      LiteralIdentifier,
	_TokenKindLowerName[622:639]: LiteralIdentifier,
	_TokenKindName[639:657]:      LiteralBlockNumber,
	_TokenKindLowerName[639:657]: LiteralBlockNumber,
	_TokenKindName[657:670]:      LiteralString,
	_TokenKindLowerName[657:670]: LiteralString,
	_TokenKindName[670:689]:      LiteralNumberFormat,
	_TokenKindLowerName[670:689]: LiteralNumberFormat,
	_TokenKindName[689:702]:      LiteralNumber,
	_TokenKindLowerName[689:702]: LiteralNumber,
	_TokenKindName[702:712]:      LiteralHex,
	_TokenKindLowerName[702:712]: LiteralHex,
	_TokenKindName[712:727]:      LiteralNumberEx,
	_TokenKindLowerName[712:727]: LiteralNumberEx,
	_TokenKindName[727:738]:      LiteralNull,
	_TokenKindLowerName[727:738]: LiteralNull,
	_TokenKindName[738:749]:      LiteralTrue,
	_TokenKindLowerName[738:749]: LiteralTrue,
	_TokenKindName[749:761]:      LiteralFalse,
	_TokenKindLowerName[749:761]: LiteralFalse,
	_TokenKindName[761:776]:      SymbolLeftParen,
	_TokenKindLowerName[761:776]: SymbolLeftParen,
	_TokenKindName[776:792]:      SymbolRightParen,
	_TokenKindLowerName[776:792]: SymbolRightParen,
	_TokenKindName[792:809]:      SymbolLeftBracket,
	_TokenKindLowerName[792:809]: SymbolLeftBracket,
	_TokenKindName[809:827]:      SymbolRightBracket,
	_TokenKindLowerName[809:827]: SymbolRightBracket,
	_TokenKindName[827:842]:      SymbolLeftBrace,
	_TokenKindLowerName[827:842]: SymbolLeftBrace,
	_TokenKindName[842:858]:      SymbolRightBrace,
	_TokenKindLowerName[842:858]: SymbolRightBrace,
	_TokenKindName[858:867]:      SymbolDot,
	_TokenKindLowerName[858:867]: SymbolDot,
	_TokenKindName[867:878]:      SymbolComma,
	_TokenKindLowerName[867:878]: SymbolComma,
	_TokenKindName[878:890]:      SymbolDollar,
	_TokenKindLowerName[878:890]: SymbolDollar,
	_TokenKindName[890:907]:      SymbolDollarParen,
	_TokenKindLowerName[890:907]: SymbolDollarParen,
	_TokenKindName[907:914]:      Comment,
	_TokenKindLowerName[907:914]: Comment,
	_TokenKindName[914:933]:      PreprocessorInclude,
	_TokenKindLowerName[914:933]: PreprocessorInclude,
	_TokenKindName[933:952]:      PreprocessorUnknown,
	_TokenKindLowerName[933:952]: PreprocessorUnknown,
	_TokenKindName[952:955]:      EOF,
	_TokenKindLowerName[952:955]: EOF,
	_TokenKindName[955:962]:      NewLine,
	_TokenKindLowerName[955:962]: NewLine,
}

var _TokenKindNames = []string{
	_TokenKindName[0:7],
	_TokenKindName[7:16],
	_TokenKindName[16:27],
	_TokenKindName[27:40],
	_TokenKindName[40:52],
	_TokenKindName[52:64],
	_TokenKindName[64:79],
	_TokenKindName[79:90],
	_TokenKindName[90:101],
	_TokenKindName[101:114],
	_TokenKindName[114:132],
	_TokenKindName[132:150],
	_TokenKindName[150:168],
	_TokenKindName[168:188],
	_TokenKindName[188:195],
	_TokenKindName[195:209],
	_TokenKindName[209:226],
	_TokenKindName[226:247],
	_TokenKindName[247:264],
	_TokenKindName[264:286],
	_TokenKindName[286:308],
	_TokenKindName[308:328],
	_TokenKindName[328:344],
	_TokenKindName[344:361],
	_TokenKindName[361:375],
	_TokenKindName[375:388],
	_TokenKindName[388:403],
	_TokenKindName[403:419],
	_TokenKindName[419:440],
	_TokenKindName[440:459],
	_TokenKindName[459:483],
	_TokenKindName[483:497],
	_TokenKindName[497:510],
	_TokenKindName[510:530],
	_TokenKindName[530:541],
	_TokenKindName[541:557],
	_TokenKindName[557:573],
	_TokenKindName[573:587],
	_TokenKindName[587:598],
	_TokenKindName[598:608],
	_TokenKindName[608:622],
	_TokenKindName[622:639],
	_TokenKindName[639:657],
	_TokenKindName[657:670],
	_TokenKindName[670:689],
	_TokenKindName[689:702],
	_TokenKindName[702:712],
	_TokenKindName[712:727],
	_TokenKindName[727:738],
	_TokenKindName[738:749],
	_TokenKindName[749:761],
	_TokenKindName[761:776],
	_TokenKindName[776:792],
	_TokenKindName[792:809],
	_TokenKindName[809:827],
	_TokenKindName[827:842],
	_TokenKindName[842:858],
	_TokenKindName[858:867],
	_TokenKindName[867:878],
	_TokenKindName[878:890],
	_TokenKindName[890:907],
	_TokenKindName[907:914],
	_TokenKindName[914:933],
	_TokenKindName[933:952],
	_TokenKindName[952:955],
	_TokenKindName[955:962],
}

// TokenKindString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func TokenKindString(s string) (TokenKind, error) {
	if val, ok := _TokenKindNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _TokenKindNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to TokenKind values", s)
}

// TokenKindValues returns all values of the enum
func TokenKindValues() []TokenKind {
	return _TokenKindValues
}

// TokenKindStrings returns a slice of all String values of the enum
func TokenKindStrings() []string {
	strs := make([]string, len(_TokenKindNames))
	copy(strs, _TokenKindNames)
	return strs
}

// IsATokenKind returns "true" if the value is listed in the enum definition. "false" otherwise
func (i TokenKind) IsATokenKind() bool {
	for _, v := range _TokenKindValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for TokenKind
func (i TokenKind) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for TokenKind
func (i *TokenKind) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("TokenKind should be a string, got %s", data)
	}

	var err error
	*i, err = TokenKindString(s)
	return err
}
