// Code generated by "enumer -type=TokenKind -json"; DO NOT EDIT.

package lexer

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _TokenKindName = "UnknownKeywordIfKeywordElseKeywordElseIfKeywordEndIfKeywordWhileKeywordEndWhileKeywordProcKeywordFuncKeywordReturnKeywordNamespaceNcKeywordNamespacePsKeywordNamespaceChanSectionOperatorAssignOperatorAssignIfBlankOperatorAddAssignOperatorSubtractAssignOperatorMultiplyAssignOperatorDivideAssignOperatorOrAssignOperatorAndAssignOperatorDeleteOperatorEqualOperatorUnequalOperatorLessThanOperatorLessThanEqualOperatorGreaterThanOperatorGreaterThanEqualOperatorLogAndOperatorLogOrOperatorStringConcatOperatorAddOperatorSubtractOperatorMultiplyOperatorDivideOperatorAndOperatorOrOperatorNegateLiteralIdentifierLiteralStringLiteralNumberFormatLiteralNumberLiteralNumberExLiteralNullLiteralTrueLiteralFalseSymbolLeftParenSymbolRightParenSymbolLeftBracketSymbolRightBracketSymbolLeftBraceSymbolRightBraceSymbolDotSymbolCommaSymbolDollarSymbolDollarParenCommentPreprocessorIncludePreprocessorUnknownEOFNewLine"

var _TokenKindIndex = [...]uint16{0, 7, 16, 27, 40, 52, 64, 79, 90, 101, 114, 132, 150, 170, 177, 191, 212, 229, 251, 273, 293, 309, 326, 340, 353, 368, 384, 405, 424, 448, 462, 475, 495, 506, 522, 538, 552, 563, 573, 587, 604, 617, 636, 649, 664, 675, 686, 698, 713, 729, 746, 764, 779, 795, 804, 815, 827, 844, 851, 870, 889, 892, 899}

const _TokenKindLowerName = "unknownkeywordifkeywordelsekeywordelseifkeywordendifkeywordwhilekeywordendwhilekeywordprockeywordfunckeywordreturnkeywordnamespacenckeywordnamespacepskeywordnamespacechansectionoperatorassignoperatorassignifblankoperatoraddassignoperatorsubtractassignoperatormultiplyassignoperatordivideassignoperatororassignoperatorandassignoperatordeleteoperatorequaloperatorunequaloperatorlessthanoperatorlessthanequaloperatorgreaterthanoperatorgreaterthanequaloperatorlogandoperatorlogoroperatorstringconcatoperatoraddoperatorsubtractoperatormultiplyoperatordivideoperatorandoperatororoperatornegateliteralidentifierliteralstringliteralnumberformatliteralnumberliteralnumberexliteralnullliteraltrueliteralfalsesymbolleftparensymbolrightparensymbolleftbracketsymbolrightbracketsymbolleftbracesymbolrightbracesymboldotsymbolcommasymboldollarsymboldollarparencommentpreprocessorincludepreprocessorunknowneofnewline"

func (i TokenKind) String() string {
	if i < 0 || i >= TokenKind(len(_TokenKindIndex)-1) {
		return fmt.Sprintf("TokenKind(%d)", i)
	}
	return _TokenKindName[_TokenKindIndex[i]:_TokenKindIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _TokenKindNoOp() {
	var x [1]struct{}
	_ = x[Unknown-(0)]
	_ = x[KeywordIf-(1)]
	_ = x[KeywordElse-(2)]
	_ = x[KeywordElseIf-(3)]
	_ = x[KeywordEndIf-(4)]
	_ = x[KeywordWhile-(5)]
	_ = x[KeywordEndWhile-(6)]
	_ = x[KeywordProc-(7)]
	_ = x[KeywordFunc-(8)]
	_ = x[KeywordReturn-(9)]
	_ = x[KeywordNamespaceNc-(10)]
	_ = x[KeywordNamespacePs-(11)]
	_ = x[KeywordNamespaceChan-(12)]
	_ = x[Section-(13)]
	_ = x[OperatorAssign-(14)]
	_ = x[OperatorAssignIfBlank-(15)]
	_ = x[OperatorAddAssign-(16)]
	_ = x[OperatorSubtractAssign-(17)]
	_ = x[OperatorMultiplyAssign-(18)]
	_ = x[OperatorDivideAssign-(19)]
	_ = x[OperatorOrAssign-(20)]
	_ = x[OperatorAndAssign-(21)]
	_ = x[OperatorDelete-(22)]
	_ = x[OperatorEqual-(23)]
	_ = x[OperatorUnequal-(24)]
	_ = x[OperatorLessThan-(25)]
	_ = x[OperatorLessThanEqual-(26)]
	_ = x[OperatorGreaterThan-(27)]
	_ = x[OperatorGreaterThanEqual-(28)]
	_ = x[OperatorLogAnd-(29)]
	_ = x[OperatorLogOr-(30)]
	_ = x[OperatorStringConcat-(31)]
	_ = x[OperatorAdd-(32)]
	_ = x[OperatorSubtract-(33)]
	_ = x[OperatorMultiply-(34)]
	_ = x[OperatorDivide-(35)]
	_ = x[OperatorAnd-(36)]
	_ = x[OperatorOr-(37)]
	_ = x[OperatorNegate-(38)]
	_ = x[LiteralIdentifier-(39)]
	_ = x[LiteralString-(40)]
	_ = x[LiteralNumberFormat-(41)]
	_ = x[LiteralNumber-(42)]
	_ = x[LiteralNumberEx-(43)]
	_ = x[LiteralNull-(44)]
	_ = x[LiteralTrue-(45)]
	_ = x[LiteralFalse-(46)]
	_ = x[SymbolLeftParen-(47)]
	_ = x[SymbolRightParen-(48)]
	_ = x[SymbolLeftBracket-(49)]
	_ = x[SymbolRightBracket-(50)]
	_ = x[SymbolLeftBrace-(51)]
	_ = x[SymbolRightBrace-(52)]
	_ = x[SymbolDot-(53)]
	_ = x[SymbolComma-(54)]
	_ = x[SymbolDollar-(55)]
	_ = x[SymbolDollarParen-(56)]
	_ = x[Comment-(57)]
	_ = x[PreprocessorInclude-(58)]
	_ = x[PreprocessorUnknown-(59)]
	_ = x[EOF-(60)]
	_ = x[NewLine-(61)]
}

var _TokenKindValues = []TokenKind{Unknown, KeywordIf, KeywordElse, KeywordElseIf, KeywordEndIf, KeywordWhile, KeywordEndWhile, KeywordProc, KeywordFunc, KeywordReturn, KeywordNamespaceNc, KeywordNamespacePs, KeywordNamespaceChan, Section, OperatorAssign, OperatorAssignIfBlank, OperatorAddAssign, OperatorSubtractAssign, OperatorMultiplyAssign, OperatorDivideAssign, OperatorOrAssign, OperatorAndAssign, OperatorDelete, OperatorEqual, OperatorUnequal, OperatorLessThan, OperatorLessThanEqual, OperatorGreaterThan, OperatorGreaterThanEqual, OperatorLogAnd, OperatorLogOr, OperatorStringConcat, OperatorAdd, OperatorSubtract, OperatorMultiply, OperatorDivide, OperatorAnd, OperatorOr, OperatorNegate, LiteralIdentifier, LiteralString, LiteralNumberFormat, LiteralNumber, LiteralNumberEx, LiteralNull, LiteralTrue, LiteralFalse, SymbolLeftParen, SymbolRightParen, SymbolLeftBracket, SymbolRightBracket, SymbolLeftBrace, SymbolRightBrace, SymbolDot, SymbolComma, SymbolDollar, SymbolDollarParen, Comment, PreprocessorInclude, PreprocessorUnknown, EOF, NewLine}

var _TokenKindNameToValueMap = map[string]TokenKind{
	_TokenKindName[0:7]:          Unknown,
	_TokenKindLowerName[0:7]:     Unknown,
	_TokenKindName[7:16]:         KeywordIf,
	_TokenKindLowerName[7:16]:    KeywordIf,
	_TokenKindName[16:27]:        KeywordElse,
	_TokenKindLowerName[16:27]:   KeywordElse,
	_TokenKindName[27:40]:        KeywordElseIf,
	_TokenKindLowerName[27:40]:   KeywordElseIf,
	_TokenKindName[40:52]:        KeywordEndIf,
	_TokenKindLowerName[40:52]:   KeywordEndIf,
	_TokenKindName[52:64]:        KeywordWhile,
	_TokenKindLowerName[52:64]:   KeywordWhile,
	_TokenKindName[64:79]:        KeywordEndWhile,
	_TokenKindLowerName[64:79]:   KeywordEndWhile,
	_TokenKindName[79:90]:        KeywordProc,
	_TokenKindLowerName[79:90]:   KeywordProc,
	_TokenKindName[90:101]:       KeywordFunc,
	_TokenKindLowerName[90:101]:  KeywordFunc,
	_TokenKindName[101:114]:      KeywordReturn,
	_TokenKindLowerName[101:114]: KeywordReturn,
	_TokenKindName[114:132]:      KeywordNamespaceNc,
	_TokenKindLowerName[114:132]: KeywordNamespaceNc,
	_TokenKindName[132:150]:      KeywordNamespacePs,
	_TokenKindLowerName[132:150]: KeywordNamespacePs,
	_TokenKindName[150:170]:      KeywordNamespaceChan,
	_TokenKindLowerName[150:170]: KeywordNamespaceChan,
	_TokenKindName[170:177]:      Section,
	_TokenKindLowerName[170:177]: Section,
	_TokenKindName[177:191]:      OperatorAssign,
	_TokenKindLowerName[177:191]: OperatorAssign,
	_TokenKindName[191:212]:      OperatorAssignIfBlank,
	_TokenKindLowerName[191:212]: OperatorAssignIfBlank,
	_TokenKindName[212:229]:      OperatorAddAssign,
	_TokenKindLowerName[212:229]: OperatorAddAssign,
	_TokenKindName[229:251]:      OperatorSubtractAssign,
	_TokenKindLowerName[229:251]: OperatorSubtractAssign,
	_TokenKindName[251:273]:      OperatorMultiplyAssign,
	_TokenKindLowerName[251:273]: OperatorMultiplyAssign,
	_TokenKindName[273:293]:      OperatorDivideAssign,
	_TokenKindLowerName[273:293]: OperatorDivideAssign,
	_TokenKindName[293:309]:      OperatorOrAssign,
	_TokenKindLowerName[293:309]: OperatorOrAssign,
	_TokenKindName[309:326]:      OperatorAndAssign,
	_TokenKindLowerName[309:326]: OperatorAndAssign,
	_TokenKindName[326:340]:      OperatorDelete,
	_TokenKindLowerName[326:340]: OperatorDelete,
	_TokenKindName[340:353]:      OperatorEqual,
	_TokenKindLowerName[340:353]: OperatorEqual,
	_TokenKindName[353:368]:      OperatorUnequal,
	_TokenKindLowerName[353:368]: OperatorUnequal,
	_TokenKindName[368:384]:      OperatorLessThan,
	_TokenKindLowerName[368:384]: OperatorLessThan,
	_TokenKindName[384:405]:      OperatorLessThanEqual,
	_TokenKindLowerName[384:405]: OperatorLessThanEqual,
	_TokenKindName[405:424]:      OperatorGreaterThan,
	_TokenKindLowerName[405:424]: OperatorGreaterThan,
	_TokenKindName[424:448]:      OperatorGreaterThanEqual,
	_TokenKindLowerName[424:448]: OperatorGreaterThanEqual,
	_TokenKindName[448:462]:      OperatorLogAnd,
	_TokenKindLowerName[448:462]: OperatorLogAnd,
	_TokenKindName[462:475]:      OperatorLogOr,
	_TokenKindLowerName[462:475]: OperatorLogOr,
	_TokenKindName[475:495]:      OperatorStringConcat,
	_TokenKindLowerName[475:495]: OperatorStringConcat,
	_TokenKindName[495:506]:      OperatorAdd,
	_TokenKindLowerName[495:506]: OperatorAdd,
	_TokenKindName[506:522]:      OperatorSubtract,
	_TokenKindLowerName[506:522]: OperatorSubtract,
	_TokenKindName[522:538]:      OperatorMultiply,
	_TokenKindLowerName[522:538]: OperatorMultiply,
	_TokenKindName[538:552]:      OperatorDivide,
	_TokenKindLowerName[538:552]: OperatorDivide,
	_TokenKindName[552:563]:      OperatorAnd,
	_TokenKindLowerName[552:563]: OperatorAnd,
	_TokenKindName[563:573]:      OperatorOr,
	_TokenKindLowerName[563:573]: OperatorOr,
	_TokenKindName[573:587]:      OperatorNegate,
	_TokenKindLowerName[573:587]: OperatorNegate,
	_TokenKindName[587:604]:      LiteralIdentifier,
	_TokenKindLowerName[587:604]: LiteralIdentifier,
	_TokenKindName[604:617]:      LiteralString,
	_TokenKindLowerName[604:617]: LiteralString,
	_TokenKindName[617:636]:      LiteralNumberFormat,
	_TokenKindLowerName[617:636]: LiteralNumberFormat,
	_TokenKindName[636:649]:      LiteralNumber,
	_TokenKindLowerName[636:649]: LiteralNumber,
	_TokenKindName[649:664]:      LiteralNumberEx,
	_TokenKindLowerName[649:664]: LiteralNumberEx,
	_TokenKindName[664:675]:      LiteralNull,
	_TokenKindLowerName[664:675]: LiteralNull,
	_TokenKindName[675:686]:      LiteralTrue,
	_TokenKindLowerName[675:686]: LiteralTrue,
	_TokenKindName[686:698]:      LiteralFalse,
	_TokenKindLowerName[686:698]: LiteralFalse,
	_TokenKindName[698:713]:      SymbolLeftParen,
	_TokenKindLowerName[698:713]: SymbolLeftParen,
	_TokenKindName[713:729]:      SymbolRightParen,
	_TokenKindLowerName[713:729]: SymbolRightParen,
	_TokenKindName[729:746]:      SymbolLeftBracket,
	_TokenKindLowerName[729:746]: SymbolLeftBracket,
	_TokenKindName[746:764]:      SymbolRightBracket,
	_TokenKindLowerName[746:764]: SymbolRightBracket,
	_TokenKindName[764:779]:      SymbolLeftBrace,
	_TokenKindLowerName[764:779]: SymbolLeftBrace,
	_TokenKindName[779:795]:      SymbolRightBrace,
	_TokenKindLowerName[779:795]: SymbolRightBrace,
	_TokenKindName[795:804]:      SymbolDot,
	_TokenKindLowerName[795:804]: SymbolDot,
	_TokenKindName[804:815]:      SymbolComma,
	_TokenKindLowerName[804:815]: SymbolComma,
	_TokenKindName[815:827]:      SymbolDollar,
	_TokenKindLowerName[815:827]: SymbolDollar,
	_TokenKindName[827:844]:      SymbolDollarParen,
	_TokenKindLowerName[827:844]: SymbolDollarParen,
	_TokenKindName[844:851]:      Comment,
	_TokenKindLowerName[844:851]: Comment,
	_TokenKindName[851:870]:      PreprocessorInclude,
	_TokenKindLowerName[851:870]: PreprocessorInclude,
	_TokenKindName[870:889]:      PreprocessorUnknown,
	_TokenKindLowerName[870:889]: PreprocessorUnknown,
	_TokenKindName[889:892]:      EOF,
	_TokenKindLowerName[889:892]: EOF,
	_TokenKindName[892:899]:      NewLine,
	_TokenKindLowerName[892:899]: NewLine,
}

var _TokenKindNames = []string{
	_TokenKindName[0:7],
	_TokenKindName[7:16],
	_TokenKindName[16:27],
	_TokenKindName[27:40],
	_TokenKindName[40:52],
	_TokenKindName[52:64],
	_TokenKindName[64:79],
	_TokenKindName[79:90],
	_TokenKindName[90:101],
	_TokenKindName[101:114],
	_TokenKindName[114:132],
	_TokenKindName[132:150],
	_TokenKindName[150:170],
	_TokenKindName[170:177],
	_TokenKindName[177:191],
	_TokenKindName[191:212],
	_TokenKindName[212:229],
	_TokenKindName[229:251],
	_TokenKindName[251:273],
	_TokenKindName[273:293],
	_TokenKindName[293:309],
	_TokenKindName[309:326],
	_TokenKindName[326:340],
	_TokenKindName[340:353],
	_TokenKindName[353:368],
	_TokenKindName[368:384],
	_TokenKindName[384:405],
	_TokenKindName[405:424],
	_TokenKindName[424:448],
	_TokenKindName[448:462],
	_TokenKindName[462:475],
	_TokenKindName[475:495],
	_TokenKindName[495:506],
	_TokenKindName[506:522],
	_TokenKindName[522:538],
	_TokenKindName[538:552],
	_TokenKindName[552:563],
	_TokenKindName[563:573],
	_TokenKindName[573:587],
	_TokenKindName[587:604],
	_TokenKindName[604:617],
	_TokenKindName[617:636],
	_TokenKindName[636:649],
	_TokenKindName[649:664],
	_TokenKindName[664:675],
	_TokenKindName[675:686],
	_TokenKindName[686:698],
	_TokenKindName[698:713],
	_TokenKindName[713:729],
	_TokenKindName[729:746],
	_TokenKindName[746:764],
	_TokenKindName[764:779],
	_TokenKindName[779:795],
	_TokenKindName[795:804],
	_TokenKindName[804:815],
	_TokenKindName[815:827],
	_TokenKindName[827:844],
	_TokenKindName[844:851],
	_TokenKindName[851:870],
	_TokenKindName[870:889],
	_TokenKindName[889:892],
	_TokenKindName[892:899],
}

// TokenKindString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func TokenKindString(s string) (TokenKind, error) {
	if val, ok := _TokenKindNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _TokenKindNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to TokenKind values", s)
}

// TokenKindValues returns all values of the enum
func TokenKindValues() []TokenKind {
	return _TokenKindValues
}

// TokenKindStrings returns a slice of all String values of the enum
func TokenKindStrings() []string {
	strs := make([]string, len(_TokenKindNames))
	copy(strs, _TokenKindNames)
	return strs
}

// IsATokenKind returns "true" if the value is listed in the enum definition. "false" otherwise
func (i TokenKind) IsATokenKind() bool {
	for _, v := range _TokenKindValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for TokenKind
func (i TokenKind) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for TokenKind
func (i *TokenKind) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("TokenKind should be a string, got %s", data)
	}

	var err error
	*i, err = TokenKindString(s)
	return err
}
