// Code generated by "enumer -type=TokenKind -json"; DO NOT EDIT.

package lexer

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _TokenKindName = "UnknownKeywordIfKeywordElseKeywordElseIfKeywordEndIfKeywordWhileKeywordEndWhileKeywordProcKeywordFuncKeywordReturnOperatorAssignOperatorAssignIfBlankOperatorAddAssignOperatorSubtractAssignOperatorMultiplyAssignOperatorDivideAssignOperatorOrAssignOperatorAndAssignOperatorDeleteOperatorEqualOperatorUnequalOperatorLessThanOperatorLessThanEqualOperatorGreaterThanOperatorGreaterThanEqualOperatorLogAndOperatorLogOrOperatorStringConcatOperatorAddOperatorSubtractOperatorMultiplyOperatorDivideOperatorAndOperatorOrOperatorNegateLiteralIdentifierLiteralStringLiteralNumberFormatLiteralNumberLiteralNumberExLiteralNullLiteralTrueLiteralFalseSymbolLeftParenSymbolRightParenSymbolLeftBracketSymbolRightBracketSymbolLeftBraceSymbolRightBraceSymbolDotSymbolCommaSymbolDollarSymbolDollarParenSectionCommentPreprocessorIncludePreprocessorUnknownEOFNewLine"

var _TokenKindIndex = [...]uint16{0, 7, 16, 27, 40, 52, 64, 79, 90, 101, 114, 128, 149, 166, 188, 210, 230, 246, 263, 277, 290, 305, 321, 342, 361, 385, 399, 412, 432, 443, 459, 475, 489, 500, 510, 524, 541, 554, 573, 586, 601, 612, 623, 635, 650, 666, 683, 701, 716, 732, 741, 752, 764, 781, 788, 795, 814, 833, 836, 843}

const _TokenKindLowerName = "unknownkeywordifkeywordelsekeywordelseifkeywordendifkeywordwhilekeywordendwhilekeywordprockeywordfunckeywordreturnoperatorassignoperatorassignifblankoperatoraddassignoperatorsubtractassignoperatormultiplyassignoperatordivideassignoperatororassignoperatorandassignoperatordeleteoperatorequaloperatorunequaloperatorlessthanoperatorlessthanequaloperatorgreaterthanoperatorgreaterthanequaloperatorlogandoperatorlogoroperatorstringconcatoperatoraddoperatorsubtractoperatormultiplyoperatordivideoperatorandoperatororoperatornegateliteralidentifierliteralstringliteralnumberformatliteralnumberliteralnumberexliteralnullliteraltrueliteralfalsesymbolleftparensymbolrightparensymbolleftbracketsymbolrightbracketsymbolleftbracesymbolrightbracesymboldotsymbolcommasymboldollarsymboldollarparensectioncommentpreprocessorincludepreprocessorunknowneofnewline"

func (i TokenKind) String() string {
	if i < 0 || i >= TokenKind(len(_TokenKindIndex)-1) {
		return fmt.Sprintf("TokenKind(%d)", i)
	}
	return _TokenKindName[_TokenKindIndex[i]:_TokenKindIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _TokenKindNoOp() {
	var x [1]struct{}
	_ = x[Unknown-(0)]
	_ = x[KeywordIf-(1)]
	_ = x[KeywordElse-(2)]
	_ = x[KeywordElseIf-(3)]
	_ = x[KeywordEndIf-(4)]
	_ = x[KeywordWhile-(5)]
	_ = x[KeywordEndWhile-(6)]
	_ = x[KeywordProc-(7)]
	_ = x[KeywordFunc-(8)]
	_ = x[KeywordReturn-(9)]
	_ = x[OperatorAssign-(10)]
	_ = x[OperatorAssignIfBlank-(11)]
	_ = x[OperatorAddAssign-(12)]
	_ = x[OperatorSubtractAssign-(13)]
	_ = x[OperatorMultiplyAssign-(14)]
	_ = x[OperatorDivideAssign-(15)]
	_ = x[OperatorOrAssign-(16)]
	_ = x[OperatorAndAssign-(17)]
	_ = x[OperatorDelete-(18)]
	_ = x[OperatorEqual-(19)]
	_ = x[OperatorUnequal-(20)]
	_ = x[OperatorLessThan-(21)]
	_ = x[OperatorLessThanEqual-(22)]
	_ = x[OperatorGreaterThan-(23)]
	_ = x[OperatorGreaterThanEqual-(24)]
	_ = x[OperatorLogAnd-(25)]
	_ = x[OperatorLogOr-(26)]
	_ = x[OperatorStringConcat-(27)]
	_ = x[OperatorAdd-(28)]
	_ = x[OperatorSubtract-(29)]
	_ = x[OperatorMultiply-(30)]
	_ = x[OperatorDivide-(31)]
	_ = x[OperatorAnd-(32)]
	_ = x[OperatorOr-(33)]
	_ = x[OperatorNegate-(34)]
	_ = x[LiteralIdentifier-(35)]
	_ = x[LiteralString-(36)]
	_ = x[LiteralNumberFormat-(37)]
	_ = x[LiteralNumber-(38)]
	_ = x[LiteralNumberEx-(39)]
	_ = x[LiteralNull-(40)]
	_ = x[LiteralTrue-(41)]
	_ = x[LiteralFalse-(42)]
	_ = x[SymbolLeftParen-(43)]
	_ = x[SymbolRightParen-(44)]
	_ = x[SymbolLeftBracket-(45)]
	_ = x[SymbolRightBracket-(46)]
	_ = x[SymbolLeftBrace-(47)]
	_ = x[SymbolRightBrace-(48)]
	_ = x[SymbolDot-(49)]
	_ = x[SymbolComma-(50)]
	_ = x[SymbolDollar-(51)]
	_ = x[SymbolDollarParen-(52)]
	_ = x[Section-(53)]
	_ = x[Comment-(54)]
	_ = x[PreprocessorInclude-(55)]
	_ = x[PreprocessorUnknown-(56)]
	_ = x[EOF-(57)]
	_ = x[NewLine-(58)]
}

var _TokenKindValues = []TokenKind{Unknown, KeywordIf, KeywordElse, KeywordElseIf, KeywordEndIf, KeywordWhile, KeywordEndWhile, KeywordProc, KeywordFunc, KeywordReturn, OperatorAssign, OperatorAssignIfBlank, OperatorAddAssign, OperatorSubtractAssign, OperatorMultiplyAssign, OperatorDivideAssign, OperatorOrAssign, OperatorAndAssign, OperatorDelete, OperatorEqual, OperatorUnequal, OperatorLessThan, OperatorLessThanEqual, OperatorGreaterThan, OperatorGreaterThanEqual, OperatorLogAnd, OperatorLogOr, OperatorStringConcat, OperatorAdd, OperatorSubtract, OperatorMultiply, OperatorDivide, OperatorAnd, OperatorOr, OperatorNegate, LiteralIdentifier, LiteralString, LiteralNumberFormat, LiteralNumber, LiteralNumberEx, LiteralNull, LiteralTrue, LiteralFalse, SymbolLeftParen, SymbolRightParen, SymbolLeftBracket, SymbolRightBracket, SymbolLeftBrace, SymbolRightBrace, SymbolDot, SymbolComma, SymbolDollar, SymbolDollarParen, Section, Comment, PreprocessorInclude, PreprocessorUnknown, EOF, NewLine}

var _TokenKindNameToValueMap = map[string]TokenKind{
	_TokenKindName[0:7]:          Unknown,
	_TokenKindLowerName[0:7]:     Unknown,
	_TokenKindName[7:16]:         KeywordIf,
	_TokenKindLowerName[7:16]:    KeywordIf,
	_TokenKindName[16:27]:        KeywordElse,
	_TokenKindLowerName[16:27]:   KeywordElse,
	_TokenKindName[27:40]:        KeywordElseIf,
	_TokenKindLowerName[27:40]:   KeywordElseIf,
	_TokenKindName[40:52]:        KeywordEndIf,
	_TokenKindLowerName[40:52]:   KeywordEndIf,
	_TokenKindName[52:64]:        KeywordWhile,
	_TokenKindLowerName[52:64]:   KeywordWhile,
	_TokenKindName[64:79]:        KeywordEndWhile,
	_TokenKindLowerName[64:79]:   KeywordEndWhile,
	_TokenKindName[79:90]:        KeywordProc,
	_TokenKindLowerName[79:90]:   KeywordProc,
	_TokenKindName[90:101]:       KeywordFunc,
	_TokenKindLowerName[90:101]:  KeywordFunc,
	_TokenKindName[101:114]:      KeywordReturn,
	_TokenKindLowerName[101:114]: KeywordReturn,
	_TokenKindName[114:128]:      OperatorAssign,
	_TokenKindLowerName[114:128]: OperatorAssign,
	_TokenKindName[128:149]:      OperatorAssignIfBlank,
	_TokenKindLowerName[128:149]: OperatorAssignIfBlank,
	_TokenKindName[149:166]:      OperatorAddAssign,
	_TokenKindLowerName[149:166]: OperatorAddAssign,
	_TokenKindName[166:188]:      OperatorSubtractAssign,
	_TokenKindLowerName[166:188]: OperatorSubtractAssign,
	_TokenKindName[188:210]:      OperatorMultiplyAssign,
	_TokenKindLowerName[188:210]: OperatorMultiplyAssign,
	_TokenKindName[210:230]:      OperatorDivideAssign,
	_TokenKindLowerName[210:230]: OperatorDivideAssign,
	_TokenKindName[230:246]:      OperatorOrAssign,
	_TokenKindLowerName[230:246]: OperatorOrAssign,
	_TokenKindName[246:263]:      OperatorAndAssign,
	_TokenKindLowerName[246:263]: OperatorAndAssign,
	_TokenKindName[263:277]:      OperatorDelete,
	_TokenKindLowerName[263:277]: OperatorDelete,
	_TokenKindName[277:290]:      OperatorEqual,
	_TokenKindLowerName[277:290]: OperatorEqual,
	_TokenKindName[290:305]:      OperatorUnequal,
	_TokenKindLowerName[290:305]: OperatorUnequal,
	_TokenKindName[305:321]:      OperatorLessThan,
	_TokenKindLowerName[305:321]: OperatorLessThan,
	_TokenKindName[321:342]:      OperatorLessThanEqual,
	_TokenKindLowerName[321:342]: OperatorLessThanEqual,
	_TokenKindName[342:361]:      OperatorGreaterThan,
	_TokenKindLowerName[342:361]: OperatorGreaterThan,
	_TokenKindName[361:385]:      OperatorGreaterThanEqual,
	_TokenKindLowerName[361:385]: OperatorGreaterThanEqual,
	_TokenKindName[385:399]:      OperatorLogAnd,
	_TokenKindLowerName[385:399]: OperatorLogAnd,
	_TokenKindName[399:412]:      OperatorLogOr,
	_TokenKindLowerName[399:412]: OperatorLogOr,
	_TokenKindName[412:432]:      OperatorStringConcat,
	_TokenKindLowerName[412:432]: OperatorStringConcat,
	_TokenKindName[432:443]:      OperatorAdd,
	_TokenKindLowerName[432:443]: OperatorAdd,
	_TokenKindName[443:459]:      OperatorSubtract,
	_TokenKindLowerName[443:459]: OperatorSubtract,
	_TokenKindName[459:475]:      OperatorMultiply,
	_TokenKindLowerName[459:475]: OperatorMultiply,
	_TokenKindName[475:489]:      OperatorDivide,
	_TokenKindLowerName[475:489]: OperatorDivide,
	_TokenKindName[489:500]:      OperatorAnd,
	_TokenKindLowerName[489:500]: OperatorAnd,
	_TokenKindName[500:510]:      OperatorOr,
	_TokenKindLowerName[500:510]: OperatorOr,
	_TokenKindName[510:524]:      OperatorNegate,
	_TokenKindLowerName[510:524]: OperatorNegate,
	_TokenKindName[524:541]:      LiteralIdentifier,
	_TokenKindLowerName[524:541]: LiteralIdentifier,
	_TokenKindName[541:554]:      LiteralString,
	_TokenKindLowerName[541:554]: LiteralString,
	_TokenKindName[554:573]:      LiteralNumberFormat,
	_TokenKindLowerName[554:573]: LiteralNumberFormat,
	_TokenKindName[573:586]:      LiteralNumber,
	_TokenKindLowerName[573:586]: LiteralNumber,
	_TokenKindName[586:601]:      LiteralNumberEx,
	_TokenKindLowerName[586:601]: LiteralNumberEx,
	_TokenKindName[601:612]:      LiteralNull,
	_TokenKindLowerName[601:612]: LiteralNull,
	_TokenKindName[612:623]:      LiteralTrue,
	_TokenKindLowerName[612:623]: LiteralTrue,
	_TokenKindName[623:635]:      LiteralFalse,
	_TokenKindLowerName[623:635]: LiteralFalse,
	_TokenKindName[635:650]:      SymbolLeftParen,
	_TokenKindLowerName[635:650]: SymbolLeftParen,
	_TokenKindName[650:666]:      SymbolRightParen,
	_TokenKindLowerName[650:666]: SymbolRightParen,
	_TokenKindName[666:683]:      SymbolLeftBracket,
	_TokenKindLowerName[666:683]: SymbolLeftBracket,
	_TokenKindName[683:701]:      SymbolRightBracket,
	_TokenKindLowerName[683:701]: SymbolRightBracket,
	_TokenKindName[701:716]:      SymbolLeftBrace,
	_TokenKindLowerName[701:716]: SymbolLeftBrace,
	_TokenKindName[716:732]:      SymbolRightBrace,
	_TokenKindLowerName[716:732]: SymbolRightBrace,
	_TokenKindName[732:741]:      SymbolDot,
	_TokenKindLowerName[732:741]: SymbolDot,
	_TokenKindName[741:752]:      SymbolComma,
	_TokenKindLowerName[741:752]: SymbolComma,
	_TokenKindName[752:764]:      SymbolDollar,
	_TokenKindLowerName[752:764]: SymbolDollar,
	_TokenKindName[764:781]:      SymbolDollarParen,
	_TokenKindLowerName[764:781]: SymbolDollarParen,
	_TokenKindName[781:788]:      Section,
	_TokenKindLowerName[781:788]: Section,
	_TokenKindName[788:795]:      Comment,
	_TokenKindLowerName[788:795]: Comment,
	_TokenKindName[795:814]:      PreprocessorInclude,
	_TokenKindLowerName[795:814]: PreprocessorInclude,
	_TokenKindName[814:833]:      PreprocessorUnknown,
	_TokenKindLowerName[814:833]: PreprocessorUnknown,
	_TokenKindName[833:836]:      EOF,
	_TokenKindLowerName[833:836]: EOF,
	_TokenKindName[836:843]:      NewLine,
	_TokenKindLowerName[836:843]: NewLine,
}

var _TokenKindNames = []string{
	_TokenKindName[0:7],
	_TokenKindName[7:16],
	_TokenKindName[16:27],
	_TokenKindName[27:40],
	_TokenKindName[40:52],
	_TokenKindName[52:64],
	_TokenKindName[64:79],
	_TokenKindName[79:90],
	_TokenKindName[90:101],
	_TokenKindName[101:114],
	_TokenKindName[114:128],
	_TokenKindName[128:149],
	_TokenKindName[149:166],
	_TokenKindName[166:188],
	_TokenKindName[188:210],
	_TokenKindName[210:230],
	_TokenKindName[230:246],
	_TokenKindName[246:263],
	_TokenKindName[263:277],
	_TokenKindName[277:290],
	_TokenKindName[290:305],
	_TokenKindName[305:321],
	_TokenKindName[321:342],
	_TokenKindName[342:361],
	_TokenKindName[361:385],
	_TokenKindName[385:399],
	_TokenKindName[399:412],
	_TokenKindName[412:432],
	_TokenKindName[432:443],
	_TokenKindName[443:459],
	_TokenKindName[459:475],
	_TokenKindName[475:489],
	_TokenKindName[489:500],
	_TokenKindName[500:510],
	_TokenKindName[510:524],
	_TokenKindName[524:541],
	_TokenKindName[541:554],
	_TokenKindName[554:573],
	_TokenKindName[573:586],
	_TokenKindName[586:601],
	_TokenKindName[601:612],
	_TokenKindName[612:623],
	_TokenKindName[623:635],
	_TokenKindName[635:650],
	_TokenKindName[650:666],
	_TokenKindName[666:683],
	_TokenKindName[683:701],
	_TokenKindName[701:716],
	_TokenKindName[716:732],
	_TokenKindName[732:741],
	_TokenKindName[741:752],
	_TokenKindName[752:764],
	_TokenKindName[764:781],
	_TokenKindName[781:788],
	_TokenKindName[788:795],
	_TokenKindName[795:814],
	_TokenKindName[814:833],
	_TokenKindName[833:836],
	_TokenKindName[836:843],
}

// TokenKindString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func TokenKindString(s string) (TokenKind, error) {
	if val, ok := _TokenKindNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _TokenKindNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to TokenKind values", s)
}

// TokenKindValues returns all values of the enum
func TokenKindValues() []TokenKind {
	return _TokenKindValues
}

// TokenKindStrings returns a slice of all String values of the enum
func TokenKindStrings() []string {
	strs := make([]string, len(_TokenKindNames))
	copy(strs, _TokenKindNames)
	return strs
}

// IsATokenKind returns "true" if the value is listed in the enum definition. "false" otherwise
func (i TokenKind) IsATokenKind() bool {
	for _, v := range _TokenKindValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for TokenKind
func (i TokenKind) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for TokenKind
func (i *TokenKind) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("TokenKind should be a string, got %s", data)
	}

	var err error
	*i, err = TokenKindString(s)
	return err
}
