// Code generated by "enumer -type=AssignmentKind -json"; DO NOT EDIT.

package parser

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _AssignmentKindName = "AssignAddAssignSubtractAssignMultiplyAssignDivideAssignAndAssignOrAssignAssignIfBlank"

var _AssignmentKindIndex = [...]uint8{0, 6, 15, 29, 43, 55, 64, 72, 85}

const _AssignmentKindLowerName = "assignaddassignsubtractassignmultiplyassigndivideassignandassignorassignassignifblank"

func (i AssignmentKind) String() string {
	if i < 0 || i >= AssignmentKind(len(_AssignmentKindIndex)-1) {
		return fmt.Sprintf("AssignmentKind(%d)", i)
	}
	return _AssignmentKindName[_AssignmentKindIndex[i]:_AssignmentKindIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _AssignmentKindNoOp() {
	var x [1]struct{}
	_ = x[Assign-(0)]
	_ = x[AddAssign-(1)]
	_ = x[SubtractAssign-(2)]
	_ = x[MultiplyAssign-(3)]
	_ = x[DivideAssign-(4)]
	_ = x[AndAssign-(5)]
	_ = x[OrAssign-(6)]
	_ = x[AssignIfBlank-(7)]
}

var _AssignmentKindValues = []AssignmentKind{Assign, AddAssign, SubtractAssign, MultiplyAssign, DivideAssign, AndAssign, OrAssign, AssignIfBlank}

var _AssignmentKindNameToValueMap = map[string]AssignmentKind{
	_AssignmentKindName[0:6]:        Assign,
	_AssignmentKindLowerName[0:6]:   Assign,
	_AssignmentKindName[6:15]:       AddAssign,
	_AssignmentKindLowerName[6:15]:  AddAssign,
	_AssignmentKindName[15:29]:      SubtractAssign,
	_AssignmentKindLowerName[15:29]: SubtractAssign,
	_AssignmentKindName[29:43]:      MultiplyAssign,
	_AssignmentKindLowerName[29:43]: MultiplyAssign,
	_AssignmentKindName[43:55]:      DivideAssign,
	_AssignmentKindLowerName[43:55]: DivideAssign,
	_AssignmentKindName[55:64]:      AndAssign,
	_AssignmentKindLowerName[55:64]: AndAssign,
	_AssignmentKindName[64:72]:      OrAssign,
	_AssignmentKindLowerName[64:72]: OrAssign,
	_AssignmentKindName[72:85]:      AssignIfBlank,
	_AssignmentKindLowerName[72:85]: AssignIfBlank,
}

var _AssignmentKindNames = []string{
	_AssignmentKindName[0:6],
	_AssignmentKindName[6:15],
	_AssignmentKindName[15:29],
	_AssignmentKindName[29:43],
	_AssignmentKindName[43:55],
	_AssignmentKindName[55:64],
	_AssignmentKindName[64:72],
	_AssignmentKindName[72:85],
}

// AssignmentKindString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func AssignmentKindString(s string) (AssignmentKind, error) {
	if val, ok := _AssignmentKindNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _AssignmentKindNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to AssignmentKind values", s)
}

// AssignmentKindValues returns all values of the enum
func AssignmentKindValues() []AssignmentKind {
	return _AssignmentKindValues
}

// AssignmentKindStrings returns a slice of all String values of the enum
func AssignmentKindStrings() []string {
	strs := make([]string, len(_AssignmentKindNames))
	copy(strs, _AssignmentKindNames)
	return strs
}

// IsAAssignmentKind returns "true" if the value is listed in the enum definition. "false" otherwise
func (i AssignmentKind) IsAAssignmentKind() bool {
	for _, v := range _AssignmentKindValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for AssignmentKind
func (i AssignmentKind) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for AssignmentKind
func (i *AssignmentKind) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("AssignmentKind should be a string, got %s", data)
	}

	var err error
	*i, err = AssignmentKindString(s)
	return err
}
