// Code generated by "enumer -type=BinaryOperator -json"; DO NOT EDIT.

package parser

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _BinaryOperatorName = "EqualNotEqualLessThanLessThanEqualGreaterThanGreaterThanEqualStringConcatAddSubtractMultiplyDivideOrAndLogicalOrLogicalAnd"

var _BinaryOperatorIndex = [...]uint8{0, 5, 13, 21, 34, 45, 61, 73, 76, 84, 92, 98, 100, 103, 112, 122}

const _BinaryOperatorLowerName = "equalnotequallessthanlessthanequalgreaterthangreaterthanequalstringconcataddsubtractmultiplydivideorandlogicalorlogicaland"

func (i BinaryOperator) String() string {
	if i < 0 || i >= BinaryOperator(len(_BinaryOperatorIndex)-1) {
		return fmt.Sprintf("BinaryOperator(%d)", i)
	}
	return _BinaryOperatorName[_BinaryOperatorIndex[i]:_BinaryOperatorIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _BinaryOperatorNoOp() {
	var x [1]struct{}
	_ = x[Equal-(0)]
	_ = x[NotEqual-(1)]
	_ = x[LessThan-(2)]
	_ = x[LessThanEqual-(3)]
	_ = x[GreaterThan-(4)]
	_ = x[GreaterThanEqual-(5)]
	_ = x[StringConcat-(6)]
	_ = x[Add-(7)]
	_ = x[Subtract-(8)]
	_ = x[Multiply-(9)]
	_ = x[Divide-(10)]
	_ = x[Or-(11)]
	_ = x[And-(12)]
	_ = x[LogicalOr-(13)]
	_ = x[LogicalAnd-(14)]
}

var _BinaryOperatorValues = []BinaryOperator{Equal, NotEqual, LessThan, LessThanEqual, GreaterThan, GreaterThanEqual, StringConcat, Add, Subtract, Multiply, Divide, Or, And, LogicalOr, LogicalAnd}

var _BinaryOperatorNameToValueMap = map[string]BinaryOperator{
	_BinaryOperatorName[0:5]:          Equal,
	_BinaryOperatorLowerName[0:5]:     Equal,
	_BinaryOperatorName[5:13]:         NotEqual,
	_BinaryOperatorLowerName[5:13]:    NotEqual,
	_BinaryOperatorName[13:21]:        LessThan,
	_BinaryOperatorLowerName[13:21]:   LessThan,
	_BinaryOperatorName[21:34]:        LessThanEqual,
	_BinaryOperatorLowerName[21:34]:   LessThanEqual,
	_BinaryOperatorName[34:45]:        GreaterThan,
	_BinaryOperatorLowerName[34:45]:   GreaterThan,
	_BinaryOperatorName[45:61]:        GreaterThanEqual,
	_BinaryOperatorLowerName[45:61]:   GreaterThanEqual,
	_BinaryOperatorName[61:73]:        StringConcat,
	_BinaryOperatorLowerName[61:73]:   StringConcat,
	_BinaryOperatorName[73:76]:        Add,
	_BinaryOperatorLowerName[73:76]:   Add,
	_BinaryOperatorName[76:84]:        Subtract,
	_BinaryOperatorLowerName[76:84]:   Subtract,
	_BinaryOperatorName[84:92]:        Multiply,
	_BinaryOperatorLowerName[84:92]:   Multiply,
	_BinaryOperatorName[92:98]:        Divide,
	_BinaryOperatorLowerName[92:98]:   Divide,
	_BinaryOperatorName[98:100]:       Or,
	_BinaryOperatorLowerName[98:100]:  Or,
	_BinaryOperatorName[100:103]:      And,
	_BinaryOperatorLowerName[100:103]: And,
	_BinaryOperatorName[103:112]:      LogicalOr,
	_BinaryOperatorLowerName[103:112]: LogicalOr,
	_BinaryOperatorName[112:122]:      LogicalAnd,
	_BinaryOperatorLowerName[112:122]: LogicalAnd,
}

var _BinaryOperatorNames = []string{
	_BinaryOperatorName[0:5],
	_BinaryOperatorName[5:13],
	_BinaryOperatorName[13:21],
	_BinaryOperatorName[21:34],
	_BinaryOperatorName[34:45],
	_BinaryOperatorName[45:61],
	_BinaryOperatorName[61:73],
	_BinaryOperatorName[73:76],
	_BinaryOperatorName[76:84],
	_BinaryOperatorName[84:92],
	_BinaryOperatorName[92:98],
	_BinaryOperatorName[98:100],
	_BinaryOperatorName[100:103],
	_BinaryOperatorName[103:112],
	_BinaryOperatorName[112:122],
}

// BinaryOperatorString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func BinaryOperatorString(s string) (BinaryOperator, error) {
	if val, ok := _BinaryOperatorNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _BinaryOperatorNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to BinaryOperator values", s)
}

// BinaryOperatorValues returns all values of the enum
func BinaryOperatorValues() []BinaryOperator {
	return _BinaryOperatorValues
}

// BinaryOperatorStrings returns a slice of all String values of the enum
func BinaryOperatorStrings() []string {
	strs := make([]string, len(_BinaryOperatorNames))
	copy(strs, _BinaryOperatorNames)
	return strs
}

// IsABinaryOperator returns "true" if the value is listed in the enum definition. "false" otherwise
func (i BinaryOperator) IsABinaryOperator() bool {
	for _, v := range _BinaryOperatorValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for BinaryOperator
func (i BinaryOperator) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for BinaryOperator
func (i *BinaryOperator) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("BinaryOperator should be a string, got %s", data)
	}

	var err error
	*i, err = BinaryOperatorString(s)
	return err
}
