// Code generated by "enumer -type=BitwiseLiteralKind -json"; DO NOT EDIT.

package parser

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _BitwiseLiteralKindName = "BinHex"

var _BitwiseLiteralKindIndex = [...]uint8{0, 3, 6}

const _BitwiseLiteralKindLowerName = "binhex"

func (i BitwiseLiteralKind) String() string {
	if i < 0 || i >= BitwiseLiteralKind(len(_BitwiseLiteralKindIndex)-1) {
		return fmt.Sprintf("BitwiseLiteralKind(%d)", i)
	}
	return _BitwiseLiteralKindName[_BitwiseLiteralKindIndex[i]:_BitwiseLiteralKindIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _BitwiseLiteralKindNoOp() {
	var x [1]struct{}
	_ = x[Bin-(0)]
	_ = x[Hex-(1)]
}

var _BitwiseLiteralKindValues = []BitwiseLiteralKind{Bin, Hex}

var _BitwiseLiteralKindNameToValueMap = map[string]BitwiseLiteralKind{
	_BitwiseLiteralKindName[0:3]:      Bin,
	_BitwiseLiteralKindLowerName[0:3]: Bin,
	_BitwiseLiteralKindName[3:6]:      Hex,
	_BitwiseLiteralKindLowerName[3:6]: Hex,
}

var _BitwiseLiteralKindNames = []string{
	_BitwiseLiteralKindName[0:3],
	_BitwiseLiteralKindName[3:6],
}

// BitwiseLiteralKindString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func BitwiseLiteralKindString(s string) (BitwiseLiteralKind, error) {
	if val, ok := _BitwiseLiteralKindNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _BitwiseLiteralKindNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to BitwiseLiteralKind values", s)
}

// BitwiseLiteralKindValues returns all values of the enum
func BitwiseLiteralKindValues() []BitwiseLiteralKind {
	return _BitwiseLiteralKindValues
}

// BitwiseLiteralKindStrings returns a slice of all String values of the enum
func BitwiseLiteralKindStrings() []string {
	strs := make([]string, len(_BitwiseLiteralKindNames))
	copy(strs, _BitwiseLiteralKindNames)
	return strs
}

// IsABitwiseLiteralKind returns "true" if the value is listed in the enum definition. "false" otherwise
func (i BitwiseLiteralKind) IsABitwiseLiteralKind() bool {
	for _, v := range _BitwiseLiteralKindValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for BitwiseLiteralKind
func (i BitwiseLiteralKind) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for BitwiseLiteralKind
func (i *BitwiseLiteralKind) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("BitwiseLiteralKind should be a string, got %s", data)
	}

	var err error
	*i, err = BitwiseLiteralKindString(s)
	return err
}
