// Code generated by "enumer -type=FunctionKind -json"; DO NOT EDIT.

package parser

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _FunctionKindName = "FunctionProcedure"

var _FunctionKindIndex = [...]uint8{0, 8, 17}

const _FunctionKindLowerName = "functionprocedure"

func (i FunctionKind) String() string {
	if i < 0 || i >= FunctionKind(len(_FunctionKindIndex)-1) {
		return fmt.Sprintf("FunctionKind(%d)", i)
	}
	return _FunctionKindName[_FunctionKindIndex[i]:_FunctionKindIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _FunctionKindNoOp() {
	var x [1]struct{}
	_ = x[Function-(0)]
	_ = x[Procedure-(1)]
}

var _FunctionKindValues = []FunctionKind{Function, Procedure}

var _FunctionKindNameToValueMap = map[string]FunctionKind{
	_FunctionKindName[0:8]:       Function,
	_FunctionKindLowerName[0:8]:  Function,
	_FunctionKindName[8:17]:      Procedure,
	_FunctionKindLowerName[8:17]: Procedure,
}

var _FunctionKindNames = []string{
	_FunctionKindName[0:8],
	_FunctionKindName[8:17],
}

// FunctionKindString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func FunctionKindString(s string) (FunctionKind, error) {
	if val, ok := _FunctionKindNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _FunctionKindNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to FunctionKind values", s)
}

// FunctionKindValues returns all values of the enum
func FunctionKindValues() []FunctionKind {
	return _FunctionKindValues
}

// FunctionKindStrings returns a slice of all String values of the enum
func FunctionKindStrings() []string {
	strs := make([]string, len(_FunctionKindNames))
	copy(strs, _FunctionKindNames)
	return strs
}

// IsAFunctionKind returns "true" if the value is listed in the enum definition. "false" otherwise
func (i FunctionKind) IsAFunctionKind() bool {
	for _, v := range _FunctionKindValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for FunctionKind
func (i FunctionKind) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for FunctionKind
func (i *FunctionKind) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("FunctionKind should be a string, got %s", data)
	}

	var err error
	*i, err = FunctionKindString(s)
	return err
}
