// Code generated by "enumer -type=PrefixOperator -json"; DO NOT EDIT.

package parser

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _PrefixOperatorName = "PlusMinusNegate"

var _PrefixOperatorIndex = [...]uint8{0, 4, 9, 15}

const _PrefixOperatorLowerName = "plusminusnegate"

func (i PrefixOperator) String() string {
	if i < 0 || i >= PrefixOperator(len(_PrefixOperatorIndex)-1) {
		return fmt.Sprintf("PrefixOperator(%d)", i)
	}
	return _PrefixOperatorName[_PrefixOperatorIndex[i]:_PrefixOperatorIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _PrefixOperatorNoOp() {
	var x [1]struct{}
	_ = x[Plus-(0)]
	_ = x[Minus-(1)]
	_ = x[Negate-(2)]
}

var _PrefixOperatorValues = []PrefixOperator{Plus, Minus, Negate}

var _PrefixOperatorNameToValueMap = map[string]PrefixOperator{
	_PrefixOperatorName[0:4]:       Plus,
	_PrefixOperatorLowerName[0:4]:  Plus,
	_PrefixOperatorName[4:9]:       Minus,
	_PrefixOperatorLowerName[4:9]:  Minus,
	_PrefixOperatorName[9:15]:      Negate,
	_PrefixOperatorLowerName[9:15]: Negate,
}

var _PrefixOperatorNames = []string{
	_PrefixOperatorName[0:4],
	_PrefixOperatorName[4:9],
	_PrefixOperatorName[9:15],
}

// PrefixOperatorString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func PrefixOperatorString(s string) (PrefixOperator, error) {
	if val, ok := _PrefixOperatorNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _PrefixOperatorNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to PrefixOperator values", s)
}

// PrefixOperatorValues returns all values of the enum
func PrefixOperatorValues() []PrefixOperator {
	return _PrefixOperatorValues
}

// PrefixOperatorStrings returns a slice of all String values of the enum
func PrefixOperatorStrings() []string {
	strs := make([]string, len(_PrefixOperatorNames))
	copy(strs, _PrefixOperatorNames)
	return strs
}

// IsAPrefixOperator returns "true" if the value is listed in the enum definition. "false" otherwise
func (i PrefixOperator) IsAPrefixOperator() bool {
	for _, v := range _PrefixOperatorValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for PrefixOperator
func (i PrefixOperator) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for PrefixOperator
func (i *PrefixOperator) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("PrefixOperator should be a string, got %s", data)
	}

	var err error
	*i, err = PrefixOperatorString(s)
	return err
}
