// Code generated by "enumer -type=SectionNamespaceKind -json"; DO NOT EDIT.

package parser

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _SectionNamespaceKindName = "UnqualifiedChandataPsNcBd"

var _SectionNamespaceKindIndex = [...]uint8{0, 11, 19, 21, 23, 25}

const _SectionNamespaceKindLowerName = "unqualifiedchandatapsncbd"

func (i SectionNamespaceKind) String() string {
	if i < 0 || i >= SectionNamespaceKind(len(_SectionNamespaceKindIndex)-1) {
		return fmt.Sprintf("SectionNamespaceKind(%d)", i)
	}
	return _SectionNamespaceKindName[_SectionNamespaceKindIndex[i]:_SectionNamespaceKindIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _SectionNamespaceKindNoOp() {
	var x [1]struct{}
	_ = x[Unqualified-(0)]
	_ = x[Chandata-(1)]
	_ = x[Ps-(2)]
	_ = x[Nc-(3)]
	_ = x[Bd-(4)]
}

var _SectionNamespaceKindValues = []SectionNamespaceKind{Unqualified, Chandata, Ps, Nc, Bd}

var _SectionNamespaceKindNameToValueMap = map[string]SectionNamespaceKind{
	_SectionNamespaceKindName[0:11]:       Unqualified,
	_SectionNamespaceKindLowerName[0:11]:  Unqualified,
	_SectionNamespaceKindName[11:19]:      Chandata,
	_SectionNamespaceKindLowerName[11:19]: Chandata,
	_SectionNamespaceKindName[19:21]:      Ps,
	_SectionNamespaceKindLowerName[19:21]: Ps,
	_SectionNamespaceKindName[21:23]:      Nc,
	_SectionNamespaceKindLowerName[21:23]: Nc,
	_SectionNamespaceKindName[23:25]:      Bd,
	_SectionNamespaceKindLowerName[23:25]: Bd,
}

var _SectionNamespaceKindNames = []string{
	_SectionNamespaceKindName[0:11],
	_SectionNamespaceKindName[11:19],
	_SectionNamespaceKindName[19:21],
	_SectionNamespaceKindName[21:23],
	_SectionNamespaceKindName[23:25],
}

// SectionNamespaceKindString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func SectionNamespaceKindString(s string) (SectionNamespaceKind, error) {
	if val, ok := _SectionNamespaceKindNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _SectionNamespaceKindNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to SectionNamespaceKind values", s)
}

// SectionNamespaceKindValues returns all values of the enum
func SectionNamespaceKindValues() []SectionNamespaceKind {
	return _SectionNamespaceKindValues
}

// SectionNamespaceKindStrings returns a slice of all String values of the enum
func SectionNamespaceKindStrings() []string {
	strs := make([]string, len(_SectionNamespaceKindNames))
	copy(strs, _SectionNamespaceKindNames)
	return strs
}

// IsASectionNamespaceKind returns "true" if the value is listed in the enum definition. "false" otherwise
func (i SectionNamespaceKind) IsASectionNamespaceKind() bool {
	for _, v := range _SectionNamespaceKindValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for SectionNamespaceKind
func (i SectionNamespaceKind) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for SectionNamespaceKind
func (i *SectionNamespaceKind) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("SectionNamespaceKind should be a string, got %s", data)
	}

	var err error
	*i, err = SectionNamespaceKindString(s)
	return err
}
